import path from 'node:path';
import ExcelJS from 'exceljs';
import { getDb } from './db.js';
import { listCompletedWhppSnapshots } from './v87WhppExportStore.js';
import { collectShopeeShipmentTruth } from './v191ShopeeTruth.js';

export const V199_EXPORT_VERSION = '2026-08-18-v199-dashboard-attempt-average-v1';
const FONT='Microsoft YaHei';
const TYPES=new Set(['CE','CEAF','TBKH','ALI1688','SHOPEECN','SHOPEEVN','WHPP']);
const SHOPEE=new Set(['SHOPEECN','SHOPEEVN']);
const POD_RE=/\bPOD\b|DELIVERED|签收|妥投|已妥投/i;
const RETURN_RE=/RETURN(?:ED|_COMPLETED)?|退回|退件/i;
const PENDING_RE=/PENDING/i;
const DELIVERY_RE=/delivery\s*assign|courier\s*assign|out\s*for\s*delivery|派件分配|分配快递员|分配派送|派送中|派件中|正在派送/i;
const STORE_RE=/(?:^|\b)(?:CP|FS)\d*[A-Z0-9_-]*\b|\bSHOP\b|CO[-\s]?SHOP|PT[-\s]?SHOP/i;
const DETAIL_HEADERS=['首次日报日期','运单编号','下单时间','状态标识','状态说明','收件省份','区域分类','当前位置/门店','收件人','收件人手机','收件地址','POD/签收时间','签收天数','派次','派次依据','派件快递员','异常描述','数据证据'];
const DETAIL_WIDTHS=[14,24,20,11,20,16,12,24,18,18,40,21,10,10,26,18,32,34];

function safeJson(v,f={}){try{return v&&typeof v==='object'?v:(JSON.parse(String(v||''))||f);}catch{return f;}}
function bill(v=''){return String(v||'').trim().toUpperCase();}
function dateKey(v=''){const m=String(v||'').match(/(\d{4})[-\/]?(\d{2})[-\/]?(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:'';}
function dayNo(v=''){const k=dateKey(v);if(!k)return null;const[y,m,d]=k.split('-').map(Number);return Date.UTC(y,m-1,d);}
function naturalDays(a,b){const x=dayNo(a),y=dayNo(b);return x===null||y===null||y<x?0:Math.floor((y-x)/86400000)+1;}
function rate(a,b){return b?Number(a||0)/Number(b):0;}
function avg(a=[]){const n=a.map(Number).filter(x=>Number.isFinite(x)&&x>0);return n.length?Number((n.reduce((s,x)=>s+x,0)/n.length).toFixed(2)):0;}
function displayType(t){return t==='SHOPEECN'?'SHOPEE CN':t==='SHOPEEVN'?'SHOPEE VN':t;}
function periodLabel(p='custom'){return({daily:'日报',weekly:'周报',monthly:'月报',custom:'自定义日期'})[p]||'区间报表';}
function safeFile(v=''){return String(v).replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,' ').trim();}
function first(o={},keys=[]){for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return '';}
function positive(...vals){for(const v of vals){const n=Number(v||0);if(Number.isFinite(n)&&n>0)return Math.min(3,Math.floor(n));}return 0;}
function listDates(from,to){const a=dayNo(from),b=dayNo(to),out=[];if(a===null||b===null||b<a)return out;for(let t=a;t<=b;t+=86400000)out.push(new Date(t).toISOString().slice(0,10));return out;}
function areaFrom(code,province=''){const c=String(code||'').trim().toUpperCase(),p=String(province||'').trim();if(c.startsWith('PP')||c==='PHNOM_PENH'||/PHNOM\s*PENH|金边/i.test(`${c} ${p}`))return'金边';if(c.startsWith('PV')||c==='PROVINCE'||p)return'外省';return'未识别';}
function isPodLike(o={}){const s=String(first(o,['currentState','scanNormalizedState','POD状态','state'])||'').toUpperCase();return Number(o.isPod||0)===1||o.是否POD==='是'||String(o.orderStatus||'')==='85'||s==='POD'||POD_RE.test(String(first(o,['状态说明','latestEventDesc','最后节点'])||''));}
function isReturnedLike(o={}){return RETURN_RE.test([o.currentState,o.退回状态,o.primaryCategory,o.currentMainCategory,o.主分类,o.异常分类,o.latestEventDesc,o.最后节点].join(' '));}
function isPendingLike(o={}){return Number(o.Pending次数||o.Pending当前次数||0)>0||PENDING_RE.test([o.currentState,o.primaryCategory,o.currentMainCategory,o.主分类,o.异常分类,o.latestEventDesc].join(' '));}
function isDeliveringLike(o={}){return Number(o.派送中停留天数||0)>0||DELIVERY_RE.test([o.currentState,o.primaryCategory,o.currentMainCategory,o.主分类,o.异常分类,o.latestEventDesc].join(' '));}
function isStoreLike(o={}){return STORE_RE.test([o.currentShop,o.currentStore,o.currentShopCode,o.targetShopCode,o.shopName,o.deliveryShop,o.当前门店].filter(Boolean).join(' '));}
function explicitPodTime(o={}){return String(first(o,['POD时间','podTime','podClosedAt','podAt','deliveredAt','deliveryCompletedAt'])||'').trim();}
function setPodEvidence(e,time,source,priority){const t=String(time||'').trim(),d=dateKey(t);if(!d)return;if(!e.podDate||priority<e.podPriority||(priority===e.podPriority&&d<e.podDate)){e.podTime=t;e.podDate=d;e.podSource=source;e.podPriority=priority;}}
function observePod(e,reportDate,source='POD日报快照'){const d=dateKey(reportDate);if(d)setPodEvidence(e,`${d} 23:59:59`,source,9);}
function eventText(r={}){const raw=safeJson(r.rawJson,{});return [r.eventCode,raw.eventCode,raw.trackingEventCode,raw.statusCode,raw.trackingEventDescZh,raw.trackingEventDesc,raw.statusText,raw.remark,raw.place,raw.eventShop,raw.locationCode].map(x=>String(x||'')).join(' ');}
function eventTime(r={}){const raw=safeJson(r.rawJson,{});return String(r.eventTime||raw.eventTime||raw.creationDate||raw.lastUpdateDate||'');}
function eventCode(r={}){const raw=safeJson(r.rawJson,{});return String(r.eventCode||raw.eventCode||raw.trackingEventCode||raw.statusCode||'');}
function newEntry(code,date,type){return{shipmentCode:code,businessType:type,firstReportDate:date,lastReportDate:date,orderTime:'',status:'',statusDesc:'',regionCode:'',province:'',area:'未识别',currentLocation:'',recipient:'',phone:'',address:'',courier:'',exceptionDesc:'',pod:false,returned:false,pending:false,delivering:false,store:false,podTime:'',podDate:'',podSource:'',podPriority:99,explicitAttempt:0,trackAttempt:0,attemptNo:0,attemptSource:'',deliveryDays:0,evidence:new Set()};}

export function resolveAttemptForV199({pod=false,explicitAttempt=0,trackAttempt=0,firstReportDate='',podDate=''}){
  if(!pod)return{attemptNo:0,source:''};const explicit=positive(explicitAttempt);if(explicit)return{attemptNo:explicit,source:'分析结果派次'};const track=positive(trackAttempt);if(track)return{attemptNo:track,source:'轨迹派送日期'};const days=naturalDays(firstReportDate,podDate);return days?{attemptNo:days>=3?3:days,source:'日报日期→POD日期兜底'}:{attemptNo:0,source:'无派次证据'};
}
export function resolveAverageDaysForV199(firstReportDate,podDate){return naturalDays(firstReportDate,podDate);}

function parseRawRow(rowJson={}){const parsed=safeJson(rowJson,{}),raw=parsed.raw&&typeof parsed.raw==='object'?parsed.raw:parsed;const get=(aliases)=>{const norm=new Map(Object.entries(raw||{}).map(([k,v])=>[String(k).normalize('NFKC').trim().toLowerCase().replace(/[\s_\-]+/g,''),v]));for(const a of aliases){const v=norm.get(String(a).normalize('NFKC').trim().toLowerCase().replace(/[\s_\-]+/g,''));if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim();}return'';};return{parsed,get};}
function latestValidBatches(db,from,to){const rows=db.prepare(`SELECT snapshotId,reportDate,createdAt,batchId FROM unified_import_batches WHERE status='VALID' AND reportDate BETWEEN ? AND ? ORDER BY reportDate,createdAt DESC,batchId DESC`).all(from,to);const m=new Map();for(const r of rows)if(!m.has(r.reportDate))m.set(r.reportDate,r);return[...m.values()];}

function seedUnified(db,type,range,onProgress){const batches=latestValidBatches(db,range.from,range.to);if(!batches.length)throw new Error(`${range.from} 至 ${range.to} 没有 VALID 日报。`);const stmt=db.prepare(`SELECT shipmentCode,regionCode,recipientRaw,recipientNormalized,rowNumber,rowJson FROM unified_import_rows WHERE snapshotId=? AND businessType=? ORDER BY rowNumber,shipmentCode`);const map=new Map();for(let i=0;i<batches.length;i++){const b=batches[i];for(const r of stmt.iterate(b.snapshotId,type)){const code=bill(r.shipmentCode);if(!code)continue;let e=map.get(code);if(!e){e=newEntry(code,b.reportDate,type);map.set(code,e);}e.firstReportDate=e.firstReportDate&&e.firstReportDate<b.reportDate?e.firstReportDate:b.reportDate;e.lastReportDate=e.lastReportDate>b.reportDate?e.lastReportDate:b.reportDate;const{parsed,get}=parseRawRow(r.rowJson);if(!e.regionCode)e.regionCode=String(r.regionCode||parsed.regionCode||'');if(!e.province)e.province=get(['收件省份','目的省份','收货省份','receiverprovince','destinationprovince']);if(!e.orderTime)e.orderTime=get(['下单时间','下单日期','订单时间','ordertime']);if(!e.recipient)e.recipient=String(r.recipientNormalized||r.recipientRaw||get(['收件人','收货人','recipient','receiver'])||'');if(!e.phone)e.phone=get(['收件人手机','收件人电话','收货人手机','手机号','receiverphone']);if(!e.address)e.address=get(['收件地址','收货地址','详细地址','receiveraddress']);const st=get(['状态标识','状态代码','status','statuscode']).toUpperCase(),desc=get(['状态说明','状态描述','statusdesc','statusdescription']);if(b.reportDate>=e.lastReportDate){e.status=st||e.status;e.statusDesc=desc||e.statusDesc;}if(st==='Y'||POD_RE.test(desc)){e.pod=true;observePod(e,b.reportDate,'首次观察POD日报日期');}if(st==='R'||RETURN_RE.test(desc))e.returned=true;if(st==='P'||PENDING_RE.test(desc))e.pending=true;if(st==='W'||DELIVERY_RE.test(desc))e.delivering=true;}onProgress({phase:'sourceRows',completed:i+1,total:batches.length,entries:map.size});}for(const e of map.values())e.area=areaFrom(e.regionCode,e.province);return map;}

function seedWhpp(range,onProgress){const snapshots=listCompletedWhppSnapshots(range.from,range.to);if(!snapshots.length)throw new Error(`${range.from} 至 ${range.to} 没有 WHPP 已完成数据。`);const map=new Map();for(let i=0;i<snapshots.length;i++){const s=snapshots[i];for(const row of s.payload?.finalRows||[]){const code=bill(first(row,['shipmentCode','运单号']));if(!code)continue;let e=map.get(code);if(!e){e=newEntry(code,s.reportDate,'WHPP');map.set(code,e);}applyFinalObject(e,row,s.reportDate,'WHPP快照');}onProgress({phase:'sourceRows',completed:i+1,total:snapshots.length,entries:map.size});}return map;}

function applyFinalObject(e,row,reportDate,source){e.lastReportDate=reportDate>=e.lastReportDate?reportDate:e.lastReportDate;e.regionCode=String(first(row,['regionCode','region_code','区域','区域分类'])||e.regionCode||'');e.province=String(first(row,['recipientProvince','收件省份','province','省份'])||e.province||'');e.area=areaFrom(e.regionCode,e.province);e.currentLocation=String(first(row,['currentShop','currentStore','currentShopCode','shopName','matchedShopName','最新节点','latestNode'])||e.currentLocation||'');e.courier=String(first(row,['courier','派件快递员','eventCourier'])||e.courier||'');e.exceptionDesc=String(first(row,['异常描述','primaryCategory','currentMainCategory','主分类','异常分类','QC判断'])||e.exceptionDesc||'');e.statusDesc=String(first(row,['currentState','scanNormalizedState','primaryCategory','currentMainCategory','主分类','异常分类'])||e.statusDesc||'');e.store=e.store||isStoreLike(row);e.explicitAttempt=positive(e.explicitAttempt,row.podAttemptNo,row.currentAttemptNo,row.派次,row.attemptNo);if(isPodLike(row)){e.pod=true;const t=explicitPodTime(row);if(t)setPodEvidence(e,t,`${source}:显式POD时间`,3);const desc=String(first(row,['latestEventDesc','最后节点'])||'');if(!t&&POD_RE.test(desc)){const lt=String(first(row,['latestEventTime','最后节点时间'])||'');if(lt)setPodEvidence(e,lt,`${source}:POD终态节点`,5);}observePod(e,reportDate,`${source}:首次观察POD日期`);}else{e.returned=e.returned||isReturnedLike(row);e.pending=e.pending||isPendingLike(row);e.delivering=e.delivering||isDeliveringLike(row);}e.evidence.add(source);}

function enrichFinalRows(db,type,map){const codes=[...map.keys()],queryType=SHOPEE.has(type)?'SHOPEE':type;for(const chunk of chunks(codes,350)){const marks=chunk.map(()=>'?').join(',');if(!marks)continue;let rows=[];try{rows=db.prepare(`SELECT shipmentCode,reportDate,isPod,primaryCategory,currentMainCategory,apiStatus,latestEventTime,latestEventDesc,latestNode,currentAttemptNo,podAttemptNo,rawJson FROM business_final_rows WHERE businessType=? AND shipmentCode IN (${marks}) ORDER BY shipmentCode,reportDate`).all(queryType,...chunk);}catch{}for(const r of rows){const e=map.get(bill(r.shipmentCode));if(!e)continue;const raw=safeJson(r.rawJson,{});applyFinalObject(e,{...raw,...r},r.reportDate,'历史分析');const t=explicitPodTime(raw);if(t)setPodEvidence(e,t,'历史分析显式POD时间',3);}}
}
function enrichCurrentState(db,type,map){const codes=[...map.keys()];for(const chunk of chunks(codes,350)){const marks=chunk.map(()=>'?').join(',');if(!marks)continue;let rows=[];try{rows=db.prepare(`SELECT shipmentCode,businessType,reportDate,state,lastEventTime,stateJson,apiStatus FROM shipment_current_state WHERE shipmentCode IN (${marks})`).all(...chunk);}catch{}for(const r of rows){const e=map.get(bill(r.shipmentCode));if(!e)continue;const bt=String(r.businessType||'').toUpperCase();if(SHOPEE.has(type)){if(![type,'SHOPEE'].includes(bt))continue;}else if(bt&&bt!==type)continue;const raw=safeJson(r.stateJson,{});applyFinalObject(e,{...raw,currentState:r.state,latestEventTime:r.lastEventTime},r.reportDate||e.lastReportDate,'当前状态');const t=explicitPodTime(raw);if(t)setPodEvidence(e,t,'当前状态显式POD时间',2);}}
}
function enrichPodLocks(db,type,map){const codes=[...map.keys()];for(const chunk of chunks(codes,500)){const marks=chunk.map(()=>'?').join(',');if(!marks)continue;let rows=[];try{if(type==='CE')rows=db.prepare(`SELECT shipmentCode,podTime,source FROM pod_locks WHERE shipmentCode IN (${marks})`).all(...chunk);else rows=db.prepare(`SELECT shipmentCode,businessType,podTime,source FROM business_pod_locks WHERE shipmentCode IN (${marks})`).all(...chunk);}catch{}for(const r of rows){const e=map.get(bill(r.shipmentCode));if(!e)continue;const bt=String(r.businessType||'').toUpperCase();if(type!=='CE'){if(SHOPEE.has(type)){if(bt&&!['SHOPEE',type].includes(bt))continue;}else if(bt&&bt!==type)continue;}if(r.podTime){e.pod=true;setPodEvidence(e,r.podTime,`POD锁:${r.source||''}`,1);e.evidence.add('POD锁');}}}
}
function enrichTracks(db,type,map){const codes=[...map.keys()],bt=SHOPEE.has(type)?'SHOPEE':type;for(const chunk of chunks(codes,250)){const marks=chunk.map(()=>'?').join(',');if(!marks)continue;let rows=[];try{rows=db.prepare(`SELECT shipmentCode,eventTime,eventCode,rawJson,createdAt FROM business_track_events WHERE businessType=? AND shipmentCode IN (${marks}) ORDER BY shipmentCode,eventTime,createdAt,id`).all(bt,...chunk);}catch{}if(type==='CE'&&!rows.length){try{rows=db.prepare(`SELECT shipmentCode,eventTime,eventCode,rawJson,createdAt FROM track_events WHERE shipmentCode IN (${marks}) ORDER BY shipmentCode,eventTime,createdAt,id`).all(...chunk);}catch{}}const by=new Map();for(const r of rows){const code=bill(r.shipmentCode);if(!map.has(code))continue;if(!by.has(code))by.set(code,[]);by.get(code).push(r);}for(const[code,events]of by){const e=map.get(code),attemptDates=new Set();for(const r of events){const text=eventText(r),tm=eventTime(r),d=dateKey(tm),c=eventCode(r);if(d&&DELIVERY_RE.test(text)&&!/盘点|cycle\s*count/i.test(text))attemptDates.add(d);if(c==='80'||POD_RE.test(text)){e.pod=true;setPodEvidence(e,tm,'POD终态轨迹',4);}}e.trackAttempt=attemptDates.size?Math.min(3,attemptDates.size):e.trackAttempt;if(attemptDates.size)e.evidence.add('派送轨迹');}}
}
function enrichShopeeTruth(db,type,map){const codes=[...map.keys()];if(!codes.length)return;const truth=collectShopeeShipmentTruth({db,businessType:type,bills:codes});for(const[code,t]of truth){const e=map.get(code);if(!e)continue;if(t.pod)e.pod=true;if(t.returned)e.returned=true;if(t.pending)e.pending=true;if(t.delivering)e.delivering=true;e.explicitAttempt=positive(e.explicitAttempt,t.attemptNo);if(t.pod&&t.eventTime)setPodEvidence(e,t.eventTime,`SHOPEE真实状态:${t.source||t.attemptSource||'终态'}`,2);for(const s of t.evidenceSources||[])e.evidence.add(s);}}
function chunks(a=[],n=350){const out=[];for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n));return out;}

function finalize(map){for(const e of map.values()){e.area=areaFrom(e.regionCode,e.province);e.store=e.store||STORE_RE.test(e.currentLocation);if(e.pod&&!e.podDate)observePod(e,e.lastReportDate||e.firstReportDate,'POD状态首次/最终观察日期');e.deliveryDays=e.pod?resolveAverageDaysForV199(e.firstReportDate,e.podDate):0;const a=resolveAttemptForV199({pod:e.pod,explicitAttempt:e.explicitAttempt,trackAttempt:e.trackAttempt,firstReportDate:e.firstReportDate,podDate:e.podDate});e.attemptNo=a.attemptNo;e.attemptSource=a.source;e.returned=!e.pod&&e.returned;e.pending=!e.pod&&!e.returned&&e.pending;e.delivering=!e.pod&&!e.returned&&!e.pending&&e.delivering;}}
async function gather(type,range,onProgress){const db=getDb(),map=type==='WHPP'?seedWhpp(range,onProgress):seedUnified(db,type,range,onProgress);enrichFinalRows(db,type,map);enrichCurrentState(db,type,map);enrichPodLocks(db,type,map);enrichTracks(db,type,map);if(SHOPEE.has(type))enrichShopeeTruth(db,type,map);finalize(map);const rows=[...map.values()].sort((a,b)=>a.firstReportDate.localeCompare(b.firstReportDate)||a.shipmentCode.localeCompare(b.shipmentCode));onProgress({phase:'truth',completed:rows.length,total:rows.length,entries:rows.filter(x=>x.evidence.size).length,validPodTimes:rows.filter(x=>x.pod&&x.podDate).length});return rows;}

function emptyStat(date=''){return{date,total:0,pp:0,pv:0,unknown:0,pod:0,notPod:0,a1:0,a2:0,a3:0,attemptUnknown:0,days:[],ppPod:0,ppA1:0,ppA2:0,ppA3:0,ppDays:[],pvPod:0,pvA1:0,pvA2:0,pvA3:0,pvDays:[],store:0,pending:0,delivering:0,returned:0,evidence:0};}
function addStat(s,e){s.total++;if(e.area==='金边')s.pp++;else if(e.area==='外省')s.pv++;else s.unknown++;if(e.store)s.store++;if(e.evidence.size)s.evidence++;if(e.pod){s.pod++;if(e.deliveryDays)s.days.push(e.deliveryDays);if(e.attemptNo===1)s.a1++;else if(e.attemptNo===2)s.a2++;else if(e.attemptNo>=3)s.a3++;else s.attemptUnknown++;if(e.area==='金边'){s.ppPod++;if(e.deliveryDays)s.ppDays.push(e.deliveryDays);if(e.attemptNo===1)s.ppA1++;else if(e.attemptNo===2)s.ppA2++;else if(e.attemptNo>=3)s.ppA3++;}if(e.area==='外省'){s.pvPod++;if(e.deliveryDays)s.pvDays.push(e.deliveryDays);if(e.attemptNo===1)s.pvA1++;else if(e.attemptNo===2)s.pvA2++;else if(e.attemptNo>=3)s.pvA3++;}}else{s.notPod++;if(e.returned)s.returned++;if(e.pending)s.pending++;if(e.delivering)s.delivering++;}}
function statsOf(rows,range){const by=new Map(listDates(range.from,range.to).map(d=>[d,emptyStat(d)])),overall=emptyStat('区间合计');for(const e of rows){if(!by.has(e.firstReportDate))by.set(e.firstReportDate,emptyStat(e.firstReportDate));addStat(by.get(e.firstReportDate),e);addStat(overall,e);}return{daily:[...by.values()].sort((a,b)=>a.date.localeCompare(b.date)),overall};}
function detailValue(e){return[e.firstReportDate,e.shipmentCode,e.orderTime,e.status,e.statusDesc,e.province,e.area,e.currentLocation,e.recipient,e.phone,e.address,e.podTime,e.deliveryDays||'',e.attemptNo?`${e.attemptNo}派`:'',e.attemptSource,e.courier,e.exceptionDesc,[...e.evidence].join('+')];}
function styleHeader(r){r.height=25;r.eachCell(c=>{c.font={name:FONT,bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF195A8D'}};c.alignment={horizontal:'center',vertical:'middle',wrapText:true};c.border={top:{style:'thin',color:{argb:'FFD6E3EF'}},bottom:{style:'thin',color:{argb:'FFD6E3EF'}},left:{style:'thin',color:{argb:'FFD6E3EF'}},right:{style:'thin',color:{argb:'FFD6E3EF'}}};});}
function styleBody(r,i){r.eachCell((c,col)=>{c.font={name:FONT,size:10,color:{argb:'FF18324F'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:i%2?'FFF8FBFF':'FFFFFFFF'}};c.alignment={vertical:'middle',horizontal:col<=8?'center':'left',wrapText:col>=9};});}
function cellStyle(c,{bold=false,size=10,color='FF18324F',fill='FFFFFFFF'}={}){c.font={name:FONT,bold,size,color:{argb:color}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:fill}};c.alignment={horizontal:'center',vertical:'middle',wrapText:true};c.border={top:{style:'thin',color:{argb:'FFD6E3EF'}},bottom:{style:'thin',color:{argb:'FFD6E3EF'}},left:{style:'thin',color:{argb:'FFD6E3EF'}},right:{style:'thin',color:{argb:'FFD6E3EF'}}};}
function addDetail(workbook,name,rows){const s=workbook.addWorksheet(name,{views:[{state:'frozen',ySplit:1}]});s.columns=DETAIL_HEADERS.map((h,i)=>({header:h,width:DETAIL_WIDTHS[i]}));styleHeader(s.getRow(1));s.autoFilter={from:'A1',to:'R1'};const anchors=new Map();let n=2;for(let i=0;i<rows.length;i++){const e=rows[i];if(!anchors.has(e.firstReportDate))anchors.set(e.firstReportDate,n);const r=s.addRow(detailValue(e));styleBody(r,i);r.commit();n++;}s.commit();return anchors;}
function link(text,sheet,row=2){return{text:String(text),hyperlink:`#'${sheet}'!A${row}`};}
function anchor(a,name,date){return a[name]?.get(date)||2;}
function pct(a,b){return b?`${(rate(a,b)*100).toFixed(2)}%`:'—';}
function fmtAvg(a){return a.length?`${avg(a).toFixed(2)}天`:'—';}
function writeCard(s,col,label,value,note,target){const letters=['A','C','E','G','I','K','M','O','Q','S'],c=letters[col],c2=String.fromCharCode(c.charCodeAt(0)+1);s.mergeCells(`${c}3:${c2}3`);s.mergeCells(`${c}4:${c2}4`);s.mergeCells(`${c}5:${c2}5`);const a=s.getCell(`${c}3`),b=s.getCell(`${c}4`),d=s.getCell(`${c}5`);a.value=label;b.value=target?link(value,target):value;d.value=note;cellStyle(a,{bold:true,size:11,fill:'FFEAF3FA'});cellStyle(b,{bold:true,size:16,color:'FF0B5EA8'});cellStyle(d,{size:9,color:'FF657B95'});}
function writeDashboard(workbook,type,range,stats,anchors){const s=workbook.addWorksheet('每日看板',{views:[{state:'frozen',ySplit:9,xSplit:1}]});s.columns=Array.from({length:37},(_,i)=>({width:i===0?14:(i===12||i===21||i===30?14:12)}));s.mergeCells('A1:AK1');const t=s.getCell('A1');t.value=`${displayType(type)} 每日数据看板（${range.from} 至 ${range.to}）`;t.font={name:FONT,bold:true,size:18,color:{argb:'FF17365D'}};t.alignment={horizontal:'center'};const o=stats.overall;writeCard(s,0,'总票数',o.total,`${o.pp}金边 / ${o.pv}外省${o.unknown?` / ${o.unknown}未识别`:''}`,'全部明细');writeCard(s,1,'POD票数',o.pod,pct(o.pod,o.total),'POD明细');writeCard(s,2,'1派POD',o.a1,pct(o.a1,o.pod));writeCard(s,3,'2派POD',o.a2,pct(o.a2,o.pod));writeCard(s,4,'3派+POD',o.a3,pct(o.a3,o.pod));writeCard(s,5,'总平均签收',fmtAvg(o.days),`有效POD日期 ${o.days.length}/${o.pod}`,'POD明细');writeCard(s,6,'金边平均签收',fmtAvg(o.ppDays),`${o.ppPod}/${o.pp} POD`,'金边明细');writeCard(s,7,'外省平均签收',fmtAvg(o.pvDays),`${o.pvPod}/${o.pv} POD`,'外省明细');writeCard(s,8,'门店票数',o.store,'门店是当前位置维度','门店明细');writeCard(s,9,'派次未识别',o.attemptUnknown,'仅无任何派次证据时');
const h=['日期','总票数','金边','外省','POD','POD率','1派POD','1派占POD','2派POD','2派占POD','3派+POD','3派+占POD','总平均天数','金边POD','金边POD率','金边1派','金边1派占POD','金边2派','金边2派占POD','金边3派+','金边3派+占POD','金边平均天数','外省POD','外省POD率','外省1派','外省1派占POD','外省2派','外省2派占POD','外省3派+','外省3派+占POD','外省平均天数','门店','Pending','派送中','退回','未POD','状态覆盖率'];const hr=s.getRow(9);h.forEach((x,i)=>hr.getCell(i+1).value=x);styleHeader(hr);let r=10;for(const d of stats.daily){const v=[d.date,d.total,d.pp,d.pv,d.pod,rate(d.pod,d.total),d.a1,rate(d.a1,d.pod),d.a2,rate(d.a2,d.pod),d.a3,rate(d.a3,d.pod),d.days.length?avg(d.days):'',d.ppPod,rate(d.ppPod,d.pp),d.ppA1,rate(d.ppA1,d.ppPod),d.ppA2,rate(d.ppA2,d.ppPod),d.ppA3,rate(d.ppA3,d.ppPod),d.ppDays.length?avg(d.ppDays):'',d.pvPod,rate(d.pvPod,d.pv),d.pvA1,rate(d.pvA1,d.pvPod),d.pvA2,rate(d.pvA2,d.pvPod),d.pvA3,rate(d.pvA3,d.pvPod),d.pvDays.length?avg(d.pvDays):'',d.store,d.pending,d.delivering,d.returned,d.notPod,rate(d.evidence,d.total)];v.forEach((x,i)=>{const c=s.getCell(r,i+1);c.value=x;cellStyle(c,{fill:r%2?'FFF8FBFF':'FFFFFFFF'});});for(const c of[6,8,10,12,15,17,19,21,24,26,28,30,37])s.getCell(r,c).numFmt='0.00%';for(const c of[13,22,31])s.getCell(r,c).numFmt='0.00';const common=[[2,'全部明细'],[3,'金边明细'],[4,'外省明细'],[5,'POD明细'],[14,'金边明细'],[23,'外省明细'],[32,'门店明细'],[33,'Pending明细'],[34,'分配派送中明细'],[35,'退回明细'],[36,'未POD明细']];for(const[col,name]of common){const c=s.getCell(r,col);c.value=link(v[col-1],name,anchor(anchors,name,d.date));c.font={name:FONT,color:{argb:'FF0563C1'},underline:true};}r++;}const nr=r+1;s.mergeCells(`A${nr}:AK${nr}`);s.getCell(`A${nr}`).value='1/2/3派只在看板统计，不再创建独立派次明细Sheet。派次优先使用分析结果/真实派送轨迹；缺失时才用首次日报日期→POD日期自然日兜底。平均签收天数使用首次日报日期→POD日期；POD日期优先POD锁/显式POD时间/POD轨迹，历史缺失时使用首次观察到POD的日报日期，避免整列空白。';s.getCell(`A${nr}`).font={name:FONT,size:10,color:{argb:'FF657B95'}};s.getCell(`A${nr}`).alignment={wrapText:true};s.getRow(nr).height=40;s.commit();}
function writeMethod(workbook,type,range){const s=workbook.addWorksheet('数据口径',{views:[{state:'frozen',ySplit:1}]});s.columns=[{width:22},{width:88},{width:66}];styleHeader(s.addRow(['项目','固定口径','精度说明']));const rows=[['业务/日期',`${displayType(type)}｜${range.from} 至 ${range.to}`,'同一运单跨日期只统计一次，按首次日报日期归属'],['1/2/3派','优先：分析结果podAttemptNo/currentAttemptNo；其次：轨迹中不同派送日期；最后：首次日报→POD日期自然日兜底','1/2/3派只显示在看板，不生成独立派次明细Sheet'],['平均签收天数','首次日报日期→POD日期自然日，包含首尾日期','POD日期优先POD锁/显式POD时间/POD终态轨迹；历史无时间时使用首次观察POD日报日期'],['金边/外省','PP/Phnom Penh=金边；PV/其他明确省份=外省','金边、外省分别计算POD、1/2/3派和平均签收天数'],['门店','CP/FS/Shop等只作为当前位置维度','不从金边/外省票数扣除'],['一致性','总票=金边+外省+未识别；POD=1派+2派+3派+未识别','校验失败则导出报错']];rows.forEach((x,i)=>{const r=s.addRow(x);styleBody(r,i);r.height=30;});s.commit();}
function reconcile(stats){const all=[...stats.daily,stats.overall];for(const x of all){if(x.total!==x.pp+x.pv+x.unknown)throw new Error(`V199区域对账失败 ${x.date}`);if(x.pod!==x.a1+x.a2+x.a3+x.attemptUnknown)throw new Error(`V199派次对账失败 ${x.date}`);}}
function writeReconcile(workbook,stats){const s=workbook.addWorksheet('99_一致性校验',{views:[{state:'frozen',ySplit:1}]});s.columns=[{width:20},{width:16},{width:16},{width:14},{width:14},{width:16}];styleHeader(s.addRow(['校验项目','左侧值','右侧值','差异','结果','范围']));for(const x of [...stats.daily,stats.overall]){for(const[c,a,b]of[['区域合计',x.total,x.pp+x.pv+x.unknown],['派次合计',x.pod,x.a1+x.a2+x.a3+x.attemptUnknown]]){const d=a-b,r=s.addRow([c,a,b,d,d===0?'通过':'失败',x.date]);styleBody(r,0);r.getCell(5).font={name:FONT,bold:true,color:{argb:d===0?'FF16803A':'FFC62828'}};}}s.commit();}

export async function createV199UnifiedDashboardWorkbook({type,periodType='custom',range,outputDir,onProgress=()=>{}}){const businessType=String(type||'').trim().toUpperCase();if(!TYPES.has(businessType))throw new Error(`V199不支持业务：${businessType}`);const rows=await gather(businessType,range,onProgress);if(!rows.length)throw new Error(`${displayType(businessType)} 在所选区间没有数据。`);const stats=statsOf(rows,range);reconcile(stats);const bucket={};const f=fn=>rows.filter(fn);bucket['全部明细']=rows;bucket['金边明细']=f(x=>x.area==='金边');bucket['外省明细']=f(x=>x.area==='外省');bucket['门店明细']=f(x=>x.store);bucket['POD明细']=f(x=>x.pod);bucket['未POD明细']=f(x=>!x.pod);bucket['分配派送中明细']=f(x=>x.delivering);bucket['Pending明细']=f(x=>x.pending);bucket['退回明细']=f(x=>x.returned);const file=path.join(outputDir,safeFile(`${displayType(businessType)}_${periodLabel(periodType)}_每日数据看板_${range.from}_至_${range.to}_V199.xlsx`));const wb=new ExcelJS.stream.xlsx.WorkbookWriter({filename:file,useStyles:true,useSharedStrings:false});wb.creator='CE Express QC';const order=['全部明细','金边明细','外省明细','门店明细','POD明细','未POD明细','分配派送中明细','Pending明细','退回明细'];const plan={};for(const name of order){plan[name]=new Map();let rr=2;for(const x of bucket[name]){if(!plan[name].has(x.firstReportDate))plan[name].set(x.firstReportDate,rr);rr++;}}writeDashboard(wb,businessType,range,stats,plan);let done=0;for(const name of order){addDetail(wb,name,bucket[name]);done++;onProgress({phase:'writing',completed:done,total:order.length,entries:rows.length,sheet:name});}writeMethod(wb,businessType,range);writeReconcile(wb,stats);await wb.commit();return{file,summary:{type:businessType,total:stats.overall.total,pod:stats.overall.pod,pp:stats.overall.pp,pv:stats.overall.pv,attempt1:stats.overall.a1,attempt2:stats.overall.a2,attempt3:stats.overall.a3,attemptUnknown:stats.overall.attemptUnknown,avgDays:avg(stats.overall.days),ppAvgDays:avg(stats.overall.ppDays),pvAvgDays:avg(stats.overall.pvDays),engine:V199_EXPORT_VERSION,outputContract:'V199_DASHBOARD_ATTEMPTS_NO_ATTEMPT_DETAIL_SHEETS'}};}
