import { getDb } from './db.js';
import { collectV205CanonicalRows, V205_CANONICAL_TRUTH_VERSION } from './v205CanonicalTruth.js';
import { listV203ManualEvidence } from './v203ManualEvidenceStore.js';
import { resolveV202AttemptCycle, v202NaturalDays } from './v202DeliveryTruth.js';

export const V205_EXPORT_TRUTH_VERSION='2026-08-18-v205-export-canonical-completeness-attempt-v1';
const SHOPEE_TYPES=new Set(['SHOPEECN','SHOPEEVN']);
const POD_RE=/\bPOD\b|DELIVERED|签收|妥投|已妥投|SUCCESSFULLY\s*DELIVERED|4004/i;
const RETURN_RE=/RETURN(?:ED|_COMPLETED)?|退回完成|已退回|退件完成|R退回|P4008/i;
const CANCEL_RE=/ORDER_CANCELLED|CANCELLED|CANCELED|订单取消|已取消|取消订单/i;
const PENDING_RE=/\bPENDING\b|派送失败|无法联系|无人接听|地址错误|\b150\b/i;
const DELIVERY_RE=/PARCEL\s*START\s*TO\s*DELIVER|OUT\s*FOR\s*DELIVERY|派送中|派件中|正在为您派送|正在派送|DELIVER\s*TO\s*BUYER|4003/i;

function safeJson(value,fallback={}){if(value&&typeof value==='object')return value;try{return JSON.parse(String(value||''))||fallback;}catch{return fallback;}}
function billOf(value=''){return String(value||'').trim().toUpperCase();}
function keyOf(value=''){return String(value||'').normalize('NFKC').trim().toLowerCase().replace(/[\s_\-]+/g,'');}
function dateKey(value=''){const m=String(value||'').match(/(\d{4})[-\/]?(\d{2})[-\/]?(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:'';}
function chunks(values=[],size=220){const out=[];for(let i=0;i<values.length;i+=size)out.push(values.slice(i,i+size));return out;}
function rawEvent(row={}){return safeJson(row.rawJson,{});}
function eventCode(row={}){const raw=rawEvent(row);return String(row.eventCode||row.shipmentStatus||raw.eventCode||raw.trackingEventCode||raw.statusCode||raw.shipmentStatus||raw.status||'').trim();}
function eventTime(row={}){const raw=rawEvent(row);return String(row.eventTime||raw.eventTime||raw.creationDate||raw.lastUpdateDate||row.updatedAt||row.createdAt||'').trim();}
function eventText(row={}){const raw=rawEvent(row);return[row.eventCode,row.shipmentStatus,row.statusText,raw.eventCode,raw.trackingEventCode,raw.statusCode,raw.shipmentStatus,raw.status,raw.statusText,raw.trackingEventDescZh,raw.trackingEventDesc,raw.trackingEventDescKm,raw.remark,raw.place,raw.locationCode,raw.eventShop].map(v=>String(v||'').trim()).filter(Boolean).join(' ');}
function eventKind(row={}){const code=eventCode(row).toUpperCase(),text=eventText(row);if(code==='80'||code==='4004'||POD_RE.test(text))return'POD';if(code==='86'||code==='P4008'||RETURN_RE.test(text))return'RETURN';if(code==='150'||PENDING_RE.test(text))return'FAIL';if(code==='70'||code==='4003'||DELIVERY_RE.test(text))return'START';return'';}
function normalizeSyntheticTime(date='',suffix='12:00:00'){return dateKey(date)?`${dateKey(date)} ${suffix}`:'';}
function firstField(objects=[],keys=[]){for(const object of objects)for(const key of keys){const value=object?.[key];if(value!==undefined&&value!==null&&String(value).trim()!=='')return String(value).trim();}return'';}
function areaOfEvidence(record={}){const text=`${record.regionCode||''} ${record.recipientProvince||''}`.toUpperCase();if(/\bPP\b|PNH|PHNOM\s*PENH|金边/.test(text))return'金边';if(/\bPV\b|PROVINCE|省/.test(text)||record.recipientProvince)return'外省';return'未识别';}
function manualEvidenceRow(record={}){const analysis=record.analysis||{},scan=record.scan||{},shipment=record.shipment||{},events=record.trackEvents||[],objects=[analysis,shipment,scan,...events];const terminal=String(record.terminalState||'OPEN').toUpperCase(),pod=terminal==='POD',returned=terminal==='RETURNED',cancelled=terminal==='CANCELLED';const latest=events.slice().sort((a,b)=>eventTime(a).localeCompare(eventTime(b))).at(-1)||{};return{firstReportDate:record.observedDate,lastReportDate:record.observedDate,shipmentCode:billOf(record.shipmentCode),businessType:record.businessType,orderTime:record.orderTime||firstField(objects,['orderTime','下单时间','下单日期','creationDate']),statusCode:firstField(objects,['statusCode','状态标识','orderStatus']),statusDesc:record.primaryCategory||record.latestEventDesc||firstField(objects,['statusDesc','状态说明','currentState','primaryCategory']),recipientProvince:record.recipientProvince||firstField(objects,['recipientProvince','收件省份','province']),area:areaOfEvidence(record),currentShop:firstField([latest,analysis,shipment],['eventShop','locationCode','currentShop','shopName']),currentProvince:firstField(objects,['currentProvince','当前省份']),recipient:firstField(objects,['recipient','收件人','recipientName']),recipientPhone:firstField(objects,['recipientPhone','收件人手机','phone']),recipientAddress:firstField(objects,['recipientAddress','收件地址','address']),rawDeliveryTime:record.podTime||'',podTime:record.podTime||'',podDate:dateKey(record.podTime),deliveryShop:firstField(objects,['deliveryShop','派件门店']),deliveryProvince:firstField(objects,['deliveryProvince','派件省份']),courier:firstField(objects,['courier','eventCourier','派件快递员']),exceptionCode:firstField(objects,['exceptionCode','异常编码']),exceptionDesc:firstField(objects,['exceptionDesc','异常描述']),remark:'手动查询/轨迹证据补录',pod,returned,cancelled,terminalNormal:pod||returned||cancelled,openUnpod:!pod&&!returned&&!cancelled,pending:!pod&&!returned&&!cancelled&&PENDING_RE.test(`${record.primaryCategory||''} ${record.latestEventDesc||''}`),delivering:!pod&&!returned&&!cancelled&&DELIVERY_RE.test(`${record.primaryCategory||''} ${record.latestEventDesc||''}`),sourceOrigin:'MANUAL_QUERY',sourceOriginLabel:'手动查询补录',metricEligible:false,manualEvidence:true,latestEventTime:record.latestEventTime||eventTime(latest),latestEventDesc:record.latestEventDesc||eventText(latest),manualEvidenceUpdatedAt:record.updatedAt||''};}
function mergeManual(rows,records){const byBill=new Map(rows.map((row,index)=>[billOf(row.shipmentCode),index]));let added=0,enriched=0;for(const record of records){const bill=billOf(record.shipmentCode),manual=manualEvidenceRow(record),index=byBill.get(bill);if(index===undefined){rows.push(manual);byBill.set(bill,rows.length-1);added++;continue;}const row=rows[index];row.manualEvidence=true;row.manualEvidenceUpdatedAt=record.updatedAt||row.manualEvidenceUpdatedAt||'';if(record.latestEventTime&&String(record.latestEventTime)>=String(row.latestEventTime||'')){row.latestEventTime=record.latestEventTime;row.latestEventDesc=record.latestEventDesc||row.latestEventDesc;}if(manual.pod){row.pod=true;row.returned=false;row.cancelled=false;row.podTime=manual.podTime||row.podTime;row.podDate=dateKey(row.podTime)||row.podDate;}else if(!row.pod&&manual.returned){row.returned=true;row.cancelled=false;}else if(!row.pod&&!row.returned&&manual.cancelled)row.cancelled=true;enriched++;}return{rows,added,enriched};}
function normalizeTerminal(row={}){const text=[row.currentState,row.scanNormalizedState,row.statusCode,row.statusDesc,row.exceptionDesc,row.remark,row.primaryCategory,row.主分类,row.异常分类,row.QC判断].map(v=>String(v||'')).join(' ');const pod=Boolean(row.pod),returned=!pod&&(Boolean(row.returned)||RETURN_RE.test(text)),cancelled=!pod&&!returned&&(Boolean(row.cancelled)||String(row.orderStatus||'')==='10'||row.订单取消==='是'||CANCEL_RE.test(text));return{...row,pod,returned,cancelled,terminalNormal:pod||returned||cancelled,openUnpod:!pod&&!returned&&!cancelled,pending:!pod&&!returned&&!cancelled&&Boolean(row.pending),delivering:!pod&&!returned&&!cancelled&&Boolean(row.delivering)};}
function parseDailyRaw(rowJson={}){const parsed=safeJson(rowJson,{}),raw=parsed?.raw&&typeof parsed.raw==='object'?parsed.raw:parsed,map=new Map(Object.entries(raw||{}).map(([k,v])=>[keyOf(k),v]));const get=aliases=>{for(const alias of aliases){const value=map.get(keyOf(alias));if(value!==undefined&&value!==null&&String(value).trim()!=='')return String(value).trim();}return'';};return{get};}
function liveAttemptEvidence(db,type,bills=[]){const map=new Map(bills.map(b=>[b,[]]));for(const part of chunks(bills)){const marks=part.map(()=>'?').join(',');if(!marks)continue;let rows=[];try{rows=db.prepare(`SELECT shipmentCode,eventTime,eventCode,rawJson,createdAt FROM business_track_events WHERE businessType IN ('SHOPEE',?) AND shipmentCode IN (${marks}) ORDER BY shipmentCode,eventTime,createdAt,id`).all(type,...part);}catch{}for(const row of rows){const bill=billOf(row.shipmentCode),kind=eventKind(row),time=eventTime(row);if(map.has(bill)&&kind&&dateKey(time))map.get(bill).push({kind,time,source:`CE轨迹${eventCode(row)||kind}`,raw:row});}}return map;}
function savedAttemptEvidence(db,type,bills=[]){const map=new Map();for(const part of chunks(bills)){const marks=part.map(()=>'?').join(',');if(!marks)continue;let rows=[];try{rows=db.prepare(`SELECT shipmentCode,rawJson FROM business_final_rows WHERE businessType IN ('SHOPEE',?) AND shipmentCode IN (${marks}) ORDER BY reportDate`).all(type,...part);}catch{}for(const row of rows){const bill=billOf(row.shipmentCode),raw=safeJson(row.rawJson,{});if(!map.has(bill))map.set(bill,[]);const list=map.get(bill),pendingDates=Array.isArray(raw.pendingDates)?raw.pendingDates:String(raw.Pending全部日期||raw.Pending日期||'').split(/[、,|;\s]+/);for(const value of pendingDates){const d=dateKey(value);if(d)list.push({kind:'FAIL',time:normalizeSyntheticTime(d,'23:00:00'),source:'保存的Pending事实日'});}const podTime=String(raw.POD时间||raw.podTime||'');if(dateKey(podTime))list.push({kind:'POD',time:podTime,source:'保存的POD时间'});}}return map;}
function dailyAttemptEvidence(db,type,rows=[]){const byBill=new Map(rows.map(row=>[billOf(row.shipmentCode),[]])),entries=new Map(rows.map(row=>[billOf(row.shipmentCode),row])),bills=[...byBill.keys()].filter(Boolean);for(const part of chunks(bills,300)){const marks=part.map(()=>'?').join(',');if(!marks)continue;let sourceRows=[];try{sourceRows=db.prepare(`SELECT shipmentCode,reportDate,rowJson FROM unified_import_rows WHERE businessType=? AND shipmentCode IN (${marks}) ORDER BY shipmentCode,reportDate,rowNumber`).all(type,...part);}catch{}for(const source of sourceRows){const bill=billOf(source.shipmentCode),entry=entries.get(bill);if(!entry)continue;const d=dateKey(source.reportDate);if(!d||d<dateKey(entry.firstReportDate)||(dateKey(entry.podDate)&&d>dateKey(entry.podDate)))continue;const{get}=parseDailyRaw(source.rowJson),status=get(['状态标识','状态代码','status','statuscode']).toUpperCase(),desc=get(['状态说明','状态描述','statusdesc','statusdescription','statusname']);if(status==='W'||status==='Y'||(DELIVERY_RE.test(desc)&&!/assign|分配/i.test(desc)))byBill.get(bill).push({kind:'START',time:normalizeSyntheticTime(d,'12:00:00'),source:`日报${status||'派送中'}真实派送状态`});if(status==='P'||PENDING_RE.test(desc))byBill.get(bill).push({kind:'FAIL',time:normalizeSyntheticTime(d,'23:00:00'),source:'日报Pending失败事实'});}}return byBill;}
function manualAttemptEvidence(records=[]){const map=new Map();for(const record of records){const bill=billOf(record.shipmentCode);if(!map.has(bill))map.set(bill,[]);for(const row of record.trackEvents||[]){const kind=eventKind(row),time=eventTime(row);if(kind&&dateKey(time))map.get(bill).push({kind,time,source:`手动查询轨迹${eventCode(row)||kind}`,raw:row});}}return map;}

export async function collectV205ExportRows(type,range,onProgress=()=>{}){
  const businessType=String(type||'').trim().toUpperCase();let rows=await collectV205CanonicalRows(businessType,range,onProgress);const manualRecords=listV203ManualEvidence({businessType,fromDate:range.from,toDate:range.to});const merged=mergeManual(rows,manualRecords);rows=merged.rows.map(normalizeTerminal);
  const db=getDb();let classified=0,unknown=0,validDays=0;
  if(SHOPEE_TYPES.has(businessType)){
    const bills=rows.map(row=>billOf(row.shipmentCode)).filter(Boolean),live=liveAttemptEvidence(db,businessType,bills),saved=savedAttemptEvidence(db,businessType,bills),daily=dailyAttemptEvidence(db,businessType,rows.filter(row=>row.metricEligible!==false)),manual=manualAttemptEvidence(manualRecords);
    for(const row of rows){const bill=billOf(row.shipmentCode),events=[...(live.get(bill)||[]),...(saved.get(bill)||[]),...(daily.get(bill)||[]),...(manual.get(bill)||[])];if(row.pod&&dateKey(row.podTime||row.podDate))events.push({kind:'POD',time:row.podTime||normalizeSyntheticTime(row.podDate,'23:59:59'),source:row.podSource||(row.manualEvidence?'手动查询POD事实':'POD事实')});const cycle=resolveV202AttemptCycle(events);row.attemptNo=row.pod?cycle.attemptNo:0;row.currentAttemptNo=cycle.currentAttemptNo;row.attemptSource=cycle.source;row.attemptEvidence=cycle.evidence.join('｜');row.attemptStartTimes=cycle.attemptStarts;row.failedAttemptDates=cycle.failureDates;row.trackAttemptNo=row.attemptNo;if(row.metricEligible!==false){if(row.pod&&row.attemptNo)classified++;else if(row.pod)unknown++;}}
  }
  for(const row of rows){row.deliveryDays=row.pod?v202NaturalDays(row.orderTime,row.podTime||row.podDate):0;row.signNaturalDays=row.deliveryDays;row.signDaySource=row.deliveryDays?'下单时间→真实POD时间（自然日，首尾计1天）':'缺少下单时间或真实POD时间';row.deliveryTruthVersion=V205_EXPORT_TRUTH_VERSION;if(row.metricEligible!==false&&row.deliveryDays>0)validDays++;}
  const official=rows.filter(row=>row.metricEligible!==false),manualOnly=rows.length-official.length,noEvidence=official.filter(row=>row.dataIntegrityReview).length;
  onProgress({phase:'v205ExportTruth',completed:rows.length,total:rows.length,businessType,officialRows:official.length,manualEvidenceOnly:manualOnly,noEvidence,classifiedAttempts:classified,attemptUnknown:unknown,validSignDays:validDays,manualEvidenceAdded:merged.added,canonicalVersion:V205_CANONICAL_TRUTH_VERSION,version:V205_EXPORT_TRUTH_VERSION});
  return rows.sort((a,b)=>String(a.firstReportDate||'').localeCompare(String(b.firstReportDate||''))||billOf(a.shipmentCode).localeCompare(billOf(b.shipmentCode)));
}
