export const V314_ALL_BUSINESS_THROUGHPUT_CORE_ID='2026-08-28-v345-all-business-bounded-retry-350-scan-50x4-track-v1';
export const V314_SHOPEE_THROUGHPUT_CORE_ID=V314_ALL_BUSINESS_THROUGHPUT_CORE_ID;
export const V339_CCSL_THROUGHPUT_CORE_ID='2026-08-28-v345-ccsl-single-lane-bounded-retry-consolidated-all-business';
export function clampInt(value,min,max,fallback){const parsed=Number(value);if(!Number.isFinite(parsed))return fallback;return Math.max(min,Math.min(max,Math.trunc(parsed)));}
export const V314_EVENT_CONCURRENCY=clampInt(process.env.TRACK_CONCURRENCY||process.env.SHOPEE_EVENT_CONCURRENCY,1,4,4);
export const V314_EXCEPTION_CONCURRENCY=clampInt(process.env.SHOPEE_EXCEPTION_CONCURRENCY,1,4,4);
export const V314_CONFIRM_CONCURRENCY=clampInt(process.env.SHOPEE_CONFIRM_CONCURRENCY,1,2,2);
export const V339_CCSL_CONFIRM_CONCURRENCY=clampInt(process.env.CCSL_CONFIRM_CONCURRENCY,1,1,1);
export const V339_CCSL_CONFIRM_HARD_BUDGET_MS=clampInt(process.env.CE_CONFIRM_HARD_BUDGET_MS,1000,30000,18000);
export function cleanShipmentCodes(values=[]){return[...new Set((values||[]).map(value=>String(value||'').trim().toUpperCase()).filter(Boolean))];}
export function splitFixedBatches(values=[],size=50){const codes=cleanShipmentCodes(values),width=Math.max(1,Number(size||1)),out=[];for(let i=0;i<codes.length;i+=width)out.push(codes.slice(i,i+width));return out;}
function batchKey(values=[]){return cleanShipmentCodes(values).join('\u001f');}
function successfulBills(statusRows=[]){return new Set((statusRows||[]).filter(row=>['success','skipped_pod','skipped_return'].includes(String(row?.status||'').toLowerCase())).map(row=>String(row?.shipmentCode||row?.waybill||row?.运单号||'').trim().toUpperCase()).filter(Boolean));}
function planBatches(sourceBills=[],completed=new Set(),width=50,mode='stable-filter'){const source=cleanShipmentCodes(sourceBills);if(mode==='compact-pending')return splitFixedBatches(source.filter(code=>!completed.has(code)),width);return splitFixedBatches(source,width).map(batch=>batch.filter(code=>!completed.has(code))).filter(batch=>batch.length);}
function runWithBudget(query,batch,budgetMs){const budget=Number(budgetMs||0);if(!(budget>0))return Promise.resolve().then(()=>query(batch));let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{const error=new Error(`confirm query exceeded ${budget}ms`);error.code='V339_CCSL_PREFETCH_HARD_TIMEOUT';reject(error);},budget);});return Promise.race([Promise.resolve().then(()=>query(batch)),timeout]).finally(()=>clearTimeout(timer));}
export function createBoundedPrefetchPool({getSourceBills,getStatusRows=()=>[],batchSize,concurrency,query,label='CE-QC',planMode='stable-filter',hardBudgetMs=0}){const width=Math.max(1,Number(batchSize||1)),limit=Math.max(1,Number(concurrency||1)),cache=new Map(),queue=[];let active=0,launched=false,plannedKeys=new Set();function pump(){while(active<limit&&queue.length){const job=queue.shift();active+=1;runWithBudget(query,job.batch,hardBudgetMs).then(value=>job.finish({ok:true,value}),error=>job.finish({ok:false,error})).finally(()=>{active-=1;pump();});}}function enqueue(batch,priority=false){const clean=cleanShipmentCodes(batch);if(!clean.length)return null;const key=batchKey(clean);if(cache.has(key))return cache.get(key);let finish;const settled=new Promise(resolve=>{finish=resolve;}),entry={key,batch:clean,settled};cache.set(key,entry);const job={key,batch:clean,finish};if(priority)queue.unshift(job);else queue.push(job);pump();return entry;}function launch(focusBatch=[]){if(launched)return;launched=true;const completed=successfulBills(getStatusRows()||[]);let batches=planBatches(getSourceBills()||[],completed,width,planMode);plannedKeys=new Set(batches.map(batchKey));const focusKey=batchKey(focusBatch);if(focusKey&&plannedKeys.has(focusKey))batches=[...batches.filter(batch=>batchKey(batch)===focusKey),...batches.filter(batch=>batchKey(batch)!==focusKey)];console.info('[CE-QC][THROUGHPUT_PREFETCH]',JSON.stringify({label,batchSize:width,concurrency:limit,batches:batches.length,completedBills:completed.size,planMode,hardBudgetMs:Number(hardBudgetMs||0),allRequestsBounded:true}));for(const batch of batches)enqueue(batch,false);}async function request(codes=[]){const batch=cleanShipmentCodes(codes);if(!batch.length)return[];launch(batch);const key=batchKey(batch);const entry=cache.get(key)||enqueue(batch,!plannedKeys.has(key));const settled=await entry.settled;if(!settled.ok){cache.delete(key);throw settled.error;}return settled.value;}return{label,batchSize:width,concurrency:limit,planMode,request,stats:()=>({active,queued:queue.length,cached:cache.size,planned:plannedKeys.size,launched,batchSize:width,concurrency:limit,hardBudgetMs:Number(hardBudgetMs||0),allRequestsBounded:true})};}
export function createUnifiedThroughputClient(state={},client,options={}){if(!client||typeof client!=='object')return client;const forced=String(options.businessType||'').toUpperCase(),isShopee=(forced||String(state.businessType||'').toUpperCase())==='SHOPEE',pools={};const label=forced||String(state.businessType||'').toUpperCase()||(isShopee?'SHOPEE':'CCSL');const confirmQuery=typeof client.confirmQuery==='function'?client.confirmQuery.bind(client):null;const trackQuery=typeof client.trackQuery==='function'?client.trackQuery.bind(client):null;const exceptionQuery=typeof client.exceptionQuery==='function'?client.exceptionQuery.bind(client):null;if(confirmQuery)pools.confirm=createBoundedPrefetchPool({getSourceBills:()=>state.scanPool||state.pnhBills||[],getStatusRows:()=>state.scanQueryStatus||[],batchSize:350,concurrency:isShopee?(options.confirmConcurrency||V314_CONFIRM_CONCURRENCY):(options.confirmConcurrency||V339_CCSL_CONFIRM_CONCURRENCY),query:confirmQuery,label:`${label}-confirm-350`,planMode:options.confirmPlanMode||(isShopee?'compact-pending':'stable-filter'),hardBudgetMs:isShopee?0:(options.hardBudgetMs||V339_CCSL_CONFIRM_HARD_BUDGET_MS)});if(trackQuery)pools.track=createBoundedPrefetchPool({getSourceBills:()=>state.needTrackBills||[],getStatusRows:()=>isShopee?(state.eventQueryStatus||[]):(state.trackQueryStatus||state.eventQueryStatus||[]),batchSize:50,concurrency:options.trackConcurrency||options.eventConcurrency||V314_EVENT_CONCURRENCY,query:trackQuery,label:`${label}-track-50`,planMode:isShopee?'stable-filter':'compact-pending'});if(exceptionQuery)pools.exception=createBoundedPrefetchPool({getSourceBills:()=>state.needExceptionBills||state.needTrackBills||[],getStatusRows:()=>state.exceptionQueryStatus||[],batchSize:50,concurrency:options.exceptionConcurrency||V314_EXCEPTION_CONCURRENCY,query:exceptionQuery,label:`${label}-exception-50`,planMode:'stable-filter'});return new Proxy(client,{get(target,prop){if(prop==='confirmQuery'&&pools.confirm)return codes=>pools.confirm.request(codes);if(prop==='trackQuery'&&pools.track)return codes=>pools.track.request(codes);if(prop==='exceptionQuery'&&pools.exception)return codes=>pools.exception.request(codes);if(prop==='__v314Pools')return pools;if(prop==='__v339CcslConfirmPool')return pools.confirm;if(prop==='__ceQcThroughputPools')return pools;const value=Reflect.get(target,prop,target);return typeof value==='function'?value.bind(target):value;}});}
export function createShopeeThroughputClient(state={},client,options={}){return createUnifiedThroughputClient(state,client,{...options,businessType:'SHOPEE'});}
export function createCcslThroughputClient(state={},client,options={}){return createUnifiedThroughputClient(state,client,{...options,businessType:'CCSL'});}
export function checkpointStrideForPhase(phase=''){const value=String(phase||'');if(/tms-shipment-event-query|exception-item-query/i.test(value))return 4;if(/SHOPEE.*订单扫描|订单扫描/i.test(value))return 2;return 1;}
export function shouldUseFastCheckpoint(state={},businessType=''){if(String(businessType||state.businessType||'').toUpperCase()!=='SHOPEE')return false;const processing=state.processing||{};if(!processing.running||processing.paused)return false;const index=Math.max(0,Number(processing.batchIndex||0)),total=Math.max(0,Number(processing.totalBatches||0));if(!index||!total||index>=total)return false;const stride=checkpointStrideForPhase(processing.phase||'');return stride>1&&index%stride!==0;}
console.info('[CE-QC][ALL_BUSINESS_THROUGHPUT_CORE]',V314_ALL_BUSINESS_THROUGHPUT_CORE_ID,'all businesses use 350-ticket confirm batches and 50-ticket track batches; track/exception prefetch is bounded x4; fallback/retry requests stay inside the same bounded owner; CCSL/WHPP confirm remains one remote 350 lane for endpoint safety.');