import express from 'express';
import { getDb, nowIso } from './db.js';
import { CEClient } from './ceClient.js';
import { analyzeV246ShopeeAttemptCycle } from './shopeeAttemptCycleV246.js';
import { ensureV246TrackingSchema, reconcileV246TrackingLedger, applyV246EvidenceRows, applyV246StrictAttemptEvidence } from './v246TrackingLedgerCore.js';

export const V320_EVIDENCE_AUTO_BACKFILL_ID='2026-08-31-v380-export-scoped-terminal-pod-backfill-v4';
const CHUNK=50,CONCURRENCY=4,MAX_DAYS=180,FOREGROUND_RETRY_MS=60_000,NETWORK_RETRY_MS=15*60_000;
const runtimeEntry=String(process.argv[1]||'');
const REAL_RUNTIME=/(?:^|[\\/])(bootstrap|server)\.js$/i.test(runtimeEntry);
const state={status:'IDLE',phase:'WAITING',total:0,completed:0,queried:0,failed:0,updated:0,unresolved:0,fromDate:'',toDate:'',businessType:'',startedAt:'',updatedAt:'',completedAt:'',message:''};
const text=v=>String(v??'').trim();
const billOf=v=>text(v).toUpperCase();
const dateKey=v=>{const m=text(v).match(/(\d{4})[-\/]?(\d{2})[-\/]?(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:'';};
const chunks=(values,size=CHUNK)=>{const out=[];for(let i=0;i<values.length;i+=size)out.push(values.slice(i,i+size));return out;};
function setState(patch,onProgress){Object.assign(state,patch,{updatedAt:nowIso()});try{onProgress?.({...state});}catch{}}
function isoMinusDays(date,days){const t=Date.parse(`${date}T00:00:00Z`);return Number.isFinite(t)?new Date(t-days*86400000).toISOString().slice(0,10):date;}
function normalizeScope(options={}){const type=text(options.businessType).toUpperCase(),from=dateKey(options.fromDate||options.from),to=dateKey(options.toDate||options.to),bills=[...new Set((options.shipmentCodes||[]).map(billOf).filter(Boolean))];return{businessType:['SHOPEECN','SHOPEEVN'].includes(type)?type:'',fromDate:from,toDate:to,shipmentCodes:bills};}
function historicalRange(db,scope={}){if(scope.fromDate&&scope.toDate&&scope.fromDate<=scope.toDate)return{fromDate:scope.fromDate,toDate:scope.toDate};ensureV246TrackingSchema(db);const typeSql=scope.businessType?' AND businessType=?':'';const params=scope.businessType?[scope.businessType]:[];const row=db.prepare(`SELECT MIN(firstReportDate) minDate,MAX(lastImportedDate) maxDate FROM qc_tracking_ledger WHERE businessType IN ('SHOPEECN','SHOPEEVN')${typeSql}`).get(...params)||{};const to=dateKey(row.maxDate),min=dateKey(row.minDate);if(!to)return null;const floor=isoMinusDays(to,MAX_DAYS-1),from=min&&min>floor?min:floor;return{fromDate:from,toDate:to};}
function processingBusy(db){try{if(db.prepare("SELECT 1 FROM run_locks WHERE status IN ('running','paused') LIMIT 1").get())return true;}catch{}try{if(db.prepare("SELECT 1 FROM business_run_locks WHERE status IN ('running','paused') LIMIT 1").get())return true;}catch{}return false;}
function localBackfillFromLedger(db,range,scope={}){
  let updated=0;const typeSql=scope.businessType?' AND businessType=?':'',params=scope.businessType?[range.toDate,range.fromDate,scope.businessType]:[range.toDate,range.fromDate];const rows=db.prepare(`SELECT shipmentCode,businessType,attemptNo,evidenceJson,lastCheckedAt FROM qc_tracking_ledger WHERE terminalReason='POD' AND businessType IN ('SHOPEECN','SHOPEEVN') AND firstReportDate<=? AND lastImportedDate>=?${typeSql} AND attemptNo>0 AND TRIM(COALESCE(CASE WHEN json_valid(evidenceJson) THEN json_extract(evidenceJson,'$.starts[0].time') END,''))<>''`).all(...params);
  const stmt=db.prepare(`UPDATE business_final_rows SET firstAttemptAt=CASE WHEN TRIM(COALESCE(firstAttemptAt,''))='' THEN ? ELSE firstAttemptAt END,podAttemptNo=CASE WHEN COALESCE(isPod,0)=1 AND ?>0 THEN ? ELSE podAttemptNo END,currentAttemptNo=CASE WHEN ?>0 THEN ? ELSE currentAttemptNo END,attemptStatus=CASE WHEN ?>0 THEN 'V380_STRICT_TRACK_BACKFILL' ELSE attemptStatus END,attemptConfidence=CASE WHEN ?>0 THEN 'HIGH' ELSE attemptConfidence END,attemptUnknownReason=CASE WHEN ?>0 THEN '' ELSE attemptUnknownReason END,attemptHistoryJson=?,attemptCalculatedAt=?,updatedAt=? WHERE UPPER(TRIM(shipmentCode))=? AND (UPPER(TRIM(businessType))='SHOPEE' OR UPPER(TRIM(businessType))=?)`);
  for(const row of rows){if(scope.shipmentCodes?.length&&!scope.shipmentCodes.includes(billOf(row.shipmentCode)))continue;let evidence={};try{evidence=JSON.parse(row.evidenceJson||'{}')||{};}catch{}const start=text(evidence?.starts?.[0]?.time);if(!start)continue;const attempt=Math.max(0,Math.min(3,Number(row.attemptNo||0))),now=nowIso(),info=JSON.stringify(evidence?.starts||[]);updated+=Number(stmt.run(start,attempt,attempt,attempt,attempt,attempt,attempt,attempt,info,now,now,billOf(row.shipmentCode),text(row.businessType).toUpperCase())?.changes||0);}return updated;
}
function candidateSql(scope,billCount){const billSql=billCount?` AND l.shipmentCode IN (${Array.from({length:billCount},()=>'?').join(',')})`:'';const typeSql=scope.businessType?' AND l.businessType=?':'';const terminalSql=billCount?'':' AND l.terminalReason=\'POD\'';return`SELECT l.shipmentCode,l.businessType,l.podDate,l.attemptNo,l.signingDays,l.evidenceJson,l.terminalReason,l.firstReportDate,l.lastImportedDate FROM qc_tracking_ledger l WHERE l.businessType IN ('SHOPEECN','SHOPEEVN') AND l.firstReportDate<=? AND l.lastImportedDate>=?${typeSql}${terminalSql}${billSql} AND (COALESCE(l.attemptNo,0)<=0 OR TRIM(COALESCE(l.podDate,''))='' OR COALESCE(l.signingDays,0)<=0 OR TRIM(COALESCE(CASE WHEN json_valid(l.evidenceJson) THEN json_extract(l.evidenceJson,'$.starts[0].time') END,''))='') ORDER BY l.firstReportDate,l.shipmentCode`;}
function candidates(db,range,scope={}){const bills=scope.shipmentCodes||[],params=[range.toDate,range.fromDate];if(scope.businessType)params.push(scope.businessType);params.push(...bills);return db.prepare(candidateSql(scope,bills.length)).all(...params);}
export function inspectV380EvidenceCandidates({businessType='',fromDate='',toDate='',shipmentCodes=[],db=getDb()}={}){ensureV246TrackingSchema(db);const scope=normalizeScope({businessType,fromDate,toDate,shipmentCodes}),range=historicalRange(db,scope);return{scope,range,rows:range?candidates(db,range,scope):[]};}
function eventBill(row={}){return billOf(row.shipmentCode||row.运单号||row.waybill||row.waybillNo||row.billCode||row.trackingNo);}
async function mapLimit(values,limit,worker){let next=0;const result=new Array(values.length);async function run(){while(true){const index=next++;if(index>=values.length)return;result[index]=await worker(values[index],index);}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,values.length))},()=>run()));return result;}
function persistFinalEvidence(db,evidenceRows){const stmt=db.prepare(`UPDATE business_final_rows SET firstAttemptAt=CASE WHEN TRIM(COALESCE(firstAttemptAt,''))='' AND ?<>'' THEN ? ELSE firstAttemptAt END,podAttemptNo=CASE WHEN COALESCE(isPod,0)=1 AND ?>0 THEN ? ELSE podAttemptNo END,currentAttemptNo=CASE WHEN ?>0 THEN ? ELSE currentAttemptNo END,attemptStatus=CASE WHEN ?>0 THEN 'V380_STRICT_TRACK_BACKFILL' ELSE attemptStatus END,attemptConfidence=CASE WHEN ?>0 THEN 'HIGH' ELSE attemptConfidence END,attemptUnknownReason=CASE WHEN ?>0 THEN '' ELSE '轨迹未取得可验证派件START' END,attemptHistoryJson=?,attemptCalculatedAt=?,updatedAt=? WHERE UPPER(TRIM(shipmentCode))=? AND (UPPER(TRIM(businessType))='SHOPEE' OR UPPER(TRIM(businessType))=?)`);let updated=0;const now=nowIso();for(const row of evidenceRows){const start=text(row.starts?.[0]?.time),attempt=Math.max(0,Math.min(3,Number(row.attemptNo||0))),history=JSON.stringify(row.starts||[]);updated+=Number(stmt.run(start,start,attempt,attempt,attempt,attempt,attempt,attempt,history,now,now,billOf(row.shipmentCode),text(row.businessType).toUpperCase())?.changes||0);}return updated;}
async function runBackfill(options={}){
  const onProgress=options.onProgress,scope=normalizeScope(options);if(state.status==='RUNNING')return{...state};const db=getDb(),range=historicalRange(db,scope);if(!range){setState({status:'COMPLETED',phase:'DONE',message:'没有需要补核的SHOPEE历史证据。',completedAt:nowIso()},onProgress);return{...state};}
  if(scope.businessType){try{reconcileV246TrackingLedger({businessType:scope.businessType,fromDate:range.fromDate,toDate:range.toDate},{db,reason:'V380_EXPORT_EVIDENCE_RECONCILE'});}catch(error){console.warn('[CE-QC][V380_EXPORT_RECONCILE_SKIPPED]',error?.message||error);}}
  if(processingBusy(db)&&options.ignoreForegroundBusy!==true){setState({status:'WAITING',phase:'FOREGROUND_BUSY',...range,businessType:scope.businessType,message:'前台七业务处理正在运行，完整表证据补核暂缓。'},onProgress);return{...state};}
  const local=localBackfillFromLedger(db,range,scope),todo=candidates(db,range,scope);setState({status:'RUNNING',phase:'TRACK_BACKFILL',...range,businessType:scope.businessType,total:todo.length,completed:0,queried:0,failed:0,updated:local,unresolved:todo.length,startedAt:nowIso(),message:todo.length?`开始补核 ${todo.length} 票完整表缺失轨迹证据。`:'已有严格证据已全部写回。'},onProgress);
  if(!todo.length){setState({status:'COMPLETED',phase:'DONE',unresolved:0,completedAt:nowIso(),message:'完整表所需真实派送/POD证据已齐。'},onProgress);return{...state};}
  const client=new CEClient(),groups=chunks(todo);let completed=0,queried=0,failed=0,updated=local;
  await mapLimit(groups,CONCURRENCY,async group=>{const bills=group.map(r=>billOf(r.shipmentCode)).filter(Boolean);let events=[];try{events=await client.trackQuery(bills);queried+=bills.length;}catch(error){failed+=bills.length;completed+=group.length;setState({completed,queried,failed,updated,message:`证据补核 ${completed}/${todo.length} · 网络失败 ${failed}票`},onProgress);return;}
    const byBill=new Map();for(const event of events||[]){const bill=eventBill(event);if(!bill)continue;if(!byBill.has(bill))byBill.set(bill,[]);byBill.get(bill).push(event);}const evidence=[];const terminalProof=[];for(const row of group){const bill=billOf(row.shipmentCode),strict=analyzeV246ShopeeAttemptCycle(byBill.get(bill)||[],{podDate:row.podDate||''}),podDate=strict.podDate||row.podDate||'';evidence.push({shipmentCode:bill,businessType:row.businessType,attemptNo:strict.attemptNo,source:strict.source,startMode:strict.startMode,starts:strict.starts,failures:strict.failures,podDate});if(podDate)terminalProof.push({shipmentCode:bill,businessType:row.businessType,pod:true,podDate,podTime:podDate,podSource:'轨迹POD',firstReportDate:row.firstReportDate,lastReportDate:row.lastImportedDate,statusDesc:'POD'});}if(terminalProof.length)applyV246EvidenceRows(terminalProof,{db,reason:'V380_EXPORT_TRACK_POD'});if(evidence.length){applyV246StrictAttemptEvidence(evidence,{db,reason:'V380_EXPORT_TRACK_BACKFILL'});updated+=persistFinalEvidence(db,evidence);}completed+=group.length;setState({completed,queried,failed,updated,message:`证据补核 ${completed}/${todo.length} · 已写回 ${updated} 条历史结果`},onProgress);});
  const unresolved=candidates(db,range,scope).length;setState({status:'COMPLETED',phase:'DONE',completed:todo.length,queried,failed,updated,unresolved,completedAt:nowIso(),message:unresolved?`补核完成；仍有 ${unresolved} 票没有取得完整真实START/POD证据，完整表将继续严格拒绝伪造。`:'补核完成：完整表所需可取得的真实轨迹证据均已写回。'},onProgress);return{...state};
}
let scheduled=false;function scheduleAfterListening(server){if(!REAL_RUNTIME||scheduled||!server)return;scheduled=true;const activate=()=>{const timer=setTimeout(async function attempt(){try{const result=await runBackfill();console.log('[CE-QC][V320_EVIDENCE_AUTO_BACKFILL]',JSON.stringify({...result,id:V320_EVIDENCE_AUTO_BACKFILL_ID}));if(result.status==='WAITING'){const retry=setTimeout(attempt,FOREGROUND_RETRY_MS);retry.unref?.();}else if(Number(result.failed||0)>0&&Number(result.unresolved||0)>0){const retry=setTimeout(attempt,NETWORK_RETRY_MS);retry.unref?.();}}catch(error){setState({status:'FAILED',phase:'FAILED',message:error?.message||String(error)});const retry=setTimeout(attempt,NETWORK_RETRY_MS);retry.unref?.();}},8000);timer.unref?.();};if(server.listening)activate();else server.once('listening',activate);}
const previousListen=express.application.listen;express.application.listen=function v320EvidenceBackfillListen(...args){const server=previousListen.apply(this,args);scheduleAfterListening(server);return server;};
export function inspectV320EvidenceBackfill(){return{id:V320_EVIDENCE_AUTO_BACKFILL_ID,...state};}
export async function runV320EvidenceBackfillNow(options={}){return runBackfill(options);}
console.info('[CE-QC][V380_EVIDENCE_REPAIR_READY]',V320_EVIDENCE_AUTO_BACKFILL_ID,'explicit export repair is scoped to missing Shopee evidence, bounded 50x4, yields to foreground QC, writes only real trajectory truth, and never fabricates START/POD dates.');
