import express from 'express';
import { getDb } from './db.js';

export const V322_WEB_AVAILABILITY_ID='2026-08-26-v322-tiny-progress-period-availability-v2';
const previousGet=express.application.get;
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const first=(...values)=>{for(const v of values)if(v!==undefined&&v!==null&&v!==''&&Number.isFinite(Number(v)))return Number(v);return 0;};
const text=v=>String(v??'').trim();
const safeJson=v=>{try{return v&&typeof v==='object'?v:(JSON.parse(String(v||'{}'))||{});}catch{return{};}};
const has=v=>v!==undefined&&v!==null&&v!==''&&Number.isFinite(Number(v));
function bounded(totalValue,doneValue,retryValue,observedValue){const total=Math.max(0,n(totalValue)),done=Math.min(total,Math.max(0,n(doneValue))),retry=Math.min(Math.max(0,total-done),Math.max(0,n(retryValue))),observed=Math.min(total,Math.max(done+retry,n(observedValue)));return{total,done,retry,observed};}
function latestValid(db){try{return db.prepare("SELECT reportDate,snapshotId FROM unified_import_batches WHERE status='VALID' ORDER BY reportDate DESC,createdAt DESC,batchId DESC LIMIT 1").get()||{};}catch{return{};}}
function latestShopeeDate(db){try{return text(db.prepare("SELECT reportDate FROM business_daily_reports WHERE businessType='SHOPEE' ORDER BY updatedAt DESC,reportDate DESC LIMIT 1").get()?.reportDate);}catch{return'';}}
function ccslSourceTotal(db,date,snapshotId){try{const mirrored=n(db.prepare('SELECT pnhCount FROM daily_reports WHERE reportDate=?').get(date)?.pnhCount);if(mirrored>0)return mirrored;}catch{}try{return n(db.prepare("SELECT COUNT(DISTINCT shipmentCode) count FROM unified_import_rows WHERE snapshotId=? AND reportDate=? AND businessType IN ('CE','CEAF','TBKH','ALI1688')").get(snapshotId,date)?.count);}catch{return 0;}}
function shopeeSourceTotal(db,date,snapshotId){try{const mirrored=n(db.prepare("SELECT totalCount FROM business_daily_reports WHERE businessType='SHOPEE' AND reportDate=?").get(date)?.totalCount);if(mirrored>0)return mirrored;}catch{}try{return n(db.prepare("SELECT COUNT(DISTINCT shipmentCode) count FROM unified_import_rows WHERE snapshotId=? AND reportDate=? AND businessType IN ('SHOPEECN','SHOPEEVN')").get(snapshotId,date)?.count);}catch{return 0;}}
function latestCheckpoint(db,type,date,runId){if(!runId)return{};try{return type==='SHOPEE'?(db.prepare("SELECT payloadJson,stage,batchIndex,totalBatches,status,errorMessage,updatedAt FROM business_run_checkpoints WHERE businessType='SHOPEE' AND reportDate=? AND runId=? ORDER BY updatedAt DESC,id DESC LIMIT 1").get(date,runId)||{}):(db.prepare('SELECT payloadJson,stage,batchIndex,totalBatches,status,errorMessage,updatedAt FROM run_checkpoints WHERE reportDate=? AND runId=? ORDER BY updatedAt DESC,rowid DESC LIMIT 1').get(date,runId)||{});}catch{return{};}}
export function readV322RunProgress(businessType='CCSL',db=getDb()){
  const type=text(businessType).toUpperCase()==='SHOPEE'?'SHOPEE':'CCSL',latest=latestValid(db);
  let date=type==='SHOPEE'?latestShopeeDate(db):'';if(!date){try{date=text(db.prepare("SELECT value FROM app_meta WHERE key='last_processed_report_date'").get()?.value);}catch{}}if(!date)date=text(latest.reportDate);
  if(!date)return{ok:true,version:V322_WEB_AVAILABILITY_ID,businessType:type,reportDate:'',running:false,paused:false,phase:'待处理',batchIndex:0,totalBatches:0,dailyTotal:0,podLockSkipped:0,scanDone:0,scanRetry:0,scanObserved:0,scanTotal:0,trackDone:0,trackRetry:0,trackObserved:0,trackTotal:0,done:0,retry:0,total:0,runId:'',runStatus:'',lastMessage:'',generatedAt:new Date().toISOString()};
  let lock={};try{lock=type==='SHOPEE'?(db.prepare("SELECT * FROM business_run_locks WHERE businessType='SHOPEE' AND reportDate=? LIMIT 1").get(date)||{}):(db.prepare('SELECT * FROM run_locks WHERE reportDate=? LIMIT 1').get(date)||{});}catch{}
  const checkpoint=latestCheckpoint(db,type,date,text(lock.runId)),payload=safeJson(checkpoint.payloadJson),last=payload.lastRunSummary||{},snapshotId=text(latest.reportDate)===date?text(latest.snapshotId):text((()=>{try{return db.prepare("SELECT snapshotId FROM unified_import_batches WHERE status='VALID' AND reportDate=? ORDER BY createdAt DESC,batchId DESC LIMIT 1").get(date)?.snapshotId;}catch{return'';}})());
  const sourceTotal=type==='SHOPEE'?shopeeSourceTotal(db,date,snapshotId):ccslSourceTotal(db,date,snapshotId);
  const scanTotal=has(payload.scanTotal)?n(payload.scanTotal):has(last.scanPool)?n(last.scanPool):sourceTotal;
  const trackTotal=has(payload.trackTotal)?n(payload.trackTotal):has(last.needTrack)?n(last.needTrack):Math.max(0,first(payload.trackDone,payload.trackResults)+first(payload.trackRetry,last.trackRetry));
  const scan=bounded(scanTotal,first(payload.scanDone,payload.scanResults),first(payload.scanRetry,last.scanRetry),first(payload.scanObserved));
  const track=bounded(trackTotal,first(payload.trackDone,payload.trackResults),first(payload.trackRetry,last.trackRetry),first(payload.trackObserved));
  const phase=text(lock.currentStage||checkpoint.stage)||'待处理',isTrack=/轨迹|track|shipment-event|exception-item/i.test(phase),status=text(lock.status).toLowerCase();
  return{ok:true,version:V322_WEB_AVAILABILITY_ID,progressRule:'V322_TINY_LOCK_CHECKPOINT_NO_FACT_TABLE_SCAN',businessType:type,reportDate:date,running:status==='running',paused:status==='paused',phase,batchIndex:first(lock.batchIndex,checkpoint.batchIndex),totalBatches:first(lock.totalBatches,checkpoint.totalBatches),dailyTotal:sourceTotal,podLockSkipped:Math.max(0,sourceTotal-scan.total),scanDone:scan.done,scanRetry:scan.retry,scanObserved:scan.observed,scanTotal:scan.total,trackDone:track.done,trackRetry:track.retry,trackObserved:track.observed,trackTotal:track.total,done:isTrack?track.done:scan.done,retry:isTrack?track.retry:scan.retry,total:isTrack?track.total:scan.total,runId:text(lock.runId),runStatus:text(payload.runStatus||last.runStatus||lock.status||checkpoint.status),lastMessage:text(lock.errorMessage||checkpoint.errorMessage),generatedAt:new Date().toISOString()};
}
function progressHandler(req,res){const started=Date.now();try{res.setHeader('Cache-Control','private,max-age=1');res.setHeader('X-CE-QC-V322',V322_WEB_AVAILABILITY_ID);const data=readV322RunProgress(req.query.businessType);res.setHeader('Server-Timing',`v322progress;dur=${Date.now()-started}`);return res.json(data);}catch(error){return res.status(200).json({ok:true,version:V322_WEB_AVAILABILITY_ID,businessType:text(req.query.businessType).toUpperCase()||'CCSL',reportDate:'',running:false,paused:false,phase:'状态读取暂缓',done:0,retry:0,total:0,error:text(error?.message||error),generatedAt:new Date().toISOString()});}}
express.application.get=function v322AvailabilityGet(pathValue,...handlers){if(String(pathValue||'')==='/api/v33/run-progress')return previousGet.call(this,pathValue,progressHandler);return previousGet.call(this,pathValue,...handlers);};
console.info('[CE-QC][V322_WEB_AVAILABILITY]',V322_WEB_AVAILABILITY_ID,'run-progress reads only tiny lock/checkpoint/membership counts; it never scans scan_results/business_scan_results/final fact tables.');
