import { getDb } from './db.js';

export const V328_THREE_BUSINESS_HISTORY_ID='2026-08-27-v328-three-business-real-history-timing-v2';
export const V328_ATTEMPT_TYPES=Object.freeze(['TBKH','SHOPEECN','SHOPEEVN']);
const TYPES=new Set(V328_ATTEMPT_TYPES);
const SHOPEE_TYPES=new Set(['SHOPEECN','SHOPEEVN']);
const CACHE_MS=30_000;
const cache=new Map();
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const pct=(a,b)=>b?Number((n(a)*100/n(b)).toFixed(2)):null;
const dateKey=v=>{const s=String(v||'').slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';};
const safeJson=v=>{try{return v&&typeof v==='object'?v:JSON.parse(String(v||'{}'));}catch{return{};}};
function hasTable(db,name){try{return Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1").get(name));}catch{return false;}}
function groupOf(type){return type==='SHOPEECN'?'CN':type==='SHOPEEVN'?'VN':'';}
function markerOf(type){return type==='SHOPEECN'?'SHOPEECN':type==='SHOPEEVN'?'SHOPEEVN':'';}
function blank(type,date){return{businessType:type,reportDate:date,total:0,matched:0,pod:0,podRate:0,ocCurrent:0,ocRate:0,sameDayPod:0,sameDayPodRate:0,attempt1:0,attempt2:0,attempt3:0,attemptUnknown:0,attemptEvidenceCount:0,attemptCoverageRate:null,dispatchSigningDaysCount:0,dispatchSigningDaysSum:0,signingDaysCount:0,signingDaysSum:0,signingSampleCount:0,signingCoverageRate:null,avgDispatchSigningDays:null,avgSigningDays:null,ready:false,ledgerReady:false,evidenceIncomplete:false,attemptEvidenceComplete:false,signingEvidenceComplete:false};}
function finish(type,row={}){const out={...blank(type,dateKey(row.reportDate)),...row};out.total=n(out.total);out.matched=n(out.matched);out.pod=n(out.pod);out.ocCurrent=n(out.ocCurrent);out.sameDayPod=n(out.sameDayPod);out.attempt1=n(out.attempt1);out.attempt2=n(out.attempt2);out.attempt3=n(out.attempt3);out.attemptEvidenceCount=out.attempt1+out.attempt2+out.attempt3;out.attemptUnknown=Math.max(0,out.pod-out.attemptEvidenceCount);out.attemptCoverageRate=pct(out.attemptEvidenceCount,out.pod);out.dispatchSigningDaysCount=n(out.dispatchSigningDaysCount);out.dispatchSigningDaysSum=n(out.dispatchSigningDaysSum);out.signingDaysCount=out.dispatchSigningDaysCount;out.signingDaysSum=out.dispatchSigningDaysSum;out.signingSampleCount=out.dispatchSigningDaysCount;out.signingCoverageRate=pct(out.dispatchSigningDaysCount,out.pod);out.avgDispatchSigningDays=out.dispatchSigningDaysCount?Number((out.dispatchSigningDaysSum/out.dispatchSigningDaysCount).toFixed(2)):null;out.avgSigningDays=out.avgDispatchSigningDays;out.podRate=pct(out.pod,out.total)??0;out.ocRate=pct(out.ocCurrent,out.total)??0;out.sameDayPodRate=pct(out.sameDayPod,out.total)??0;out.ready=Boolean(row.summaryReady)||(out.total>0&&out.matched>=out.total);out.ledgerReady=true;out.attemptEvidenceComplete=out.pod===0||out.attemptUnknown===0;out.signingEvidenceComplete=out.pod===0||out.dispatchSigningDaysCount>=out.pod;out.evidenceIncomplete=out.ready&&out.pod>0&&(!out.attemptEvidenceComplete||!out.signingEvidenceComplete);return out;}

function rangeClause(upperOnly){return upperOnly?'reportDate<=?':'reportDate BETWEEN ? AND ?';}
function rangeParams({from,to,upperOnly}){return upperOnly?[to]:[from,to];}
function membershipUnion(type,{from='',to='',db=getDb(),upperOnly=false}={}){
  const parts=[],params=[],range=rangeClause(upperOnly),rp=rangeParams({from,to,upperOnly});
  if(hasTable(db,'unified_import_rows')){
    parts.push(`SELECT reportDate,shipmentCode FROM unified_import_rows WHERE businessType=? AND ${range} AND shipmentCode<>''`);params.push(type,...rp);
    if(SHOPEE_TYPES.has(type)){const marker=`%${markerOf(type)}%`;parts.push(`SELECT reportDate,shipmentCode FROM unified_import_rows WHERE businessType='SHOPEE' AND ${range} AND shipmentCode<>'' AND (UPPER(COALESCE(recipientRaw,'')) LIKE ? OR UPPER(COALESCE(recipientNormalized,'')) LIKE ? OR UPPER(COALESCE(rowJson,'')) LIKE ?)`);params.push(...rp,marker,marker,marker);}
  }
  if(hasTable(db,'shipment_daily_snapshots')){
    parts.push(`SELECT reportDate,shipmentCode FROM shipment_daily_snapshots WHERE businessType=? AND ${range} AND shipmentCode<>''`);params.push(type,...rp);
    if(SHOPEE_TYPES.has(type)){const marker=`%${markerOf(type)}%`;parts.push(`SELECT reportDate,shipmentCode FROM shipment_daily_snapshots WHERE businessType='SHOPEE' AND ${range} AND shipmentCode<>'' AND UPPER(COALESCE(rowJson,'')) LIKE ?`);params.push(...rp,marker);}
  }
  if(SHOPEE_TYPES.has(type)&&hasTable(db,'business_daily_parse_rows')){
    const group=groupOf(type),marker=`%${markerOf(type)}%`;
    parts.push(`SELECT reportDate,shipmentCode FROM business_daily_parse_rows WHERE businessType IN ('SHOPEE',?) AND ${range} AND shipmentCode<>'' AND (recipient_group=? OR UPPER(COALESCE(recipient_raw,'')) LIKE ? OR UPPER(COALESCE(recipient_normalized,'')) LIKE ? OR UPPER(COALESCE(rowJson,'')) LIKE ?)`);params.push(type,...rp,group,marker,marker,marker);
  }
  return{sql:parts.length?parts.join(' UNION ALL '):`SELECT '' reportDate,'' shipmentCode WHERE 0`,params};
}
function explicitGroupSummary(summary,group){const roots=[summary?.groups?.[group],summary?.recipientGroups?.[group],summary?.recipient_groups?.[group],summary?.dashboard?.groups?.[group],summary?.dashboard?.recipientGroups?.[group],summary?.[group]].filter(v=>v&&typeof v==='object');for(const src of roots){const total=[src.total,src.sourceTotal,src.totalCount,src.ticket,src.tickets].find(v=>Number.isFinite(Number(v)));if(total===undefined)continue;const pod=[src.pod,src.podCount,src.todayPod].find(v=>Number.isFinite(Number(v)));const oc=[src.ocCurrent,src.oc,src.ocCount].find(v=>Number.isFinite(Number(v)));const same=[src.sameDayPod,src.firstDayPod].find(v=>Number.isFinite(Number(v)));return{total:n(total),matched:n(total),pod:n(pod),ocCurrent:n(oc),sameDayPod:n(same),summaryReady:true};}return null;}
function summaryFallback(type,to,db){const out=new Map();if(!SHOPEE_TYPES.has(type)||!hasTable(db,'business_history_summary'))return out;const group=groupOf(type);try{for(const r of db.prepare(`SELECT reportDate,summaryJson FROM business_history_summary WHERE businessType IN ('SHOPEE',?) AND reportDate<=? ORDER BY reportDate`).all(type,to)){const d=dateKey(r.reportDate),fact=explicitGroupSummary(safeJson(r.summaryJson),group);if(d&&fact&&fact.total>0)out.set(d,finish(type,{...fact,reportDate:d}));}}catch{}return out;}
function censusDates(type,toDate,db){const to=dateKey(toDate);if(!to)return[];const set=new Set(),members=membershipUnion(type,{to,db,upperOnly:true});try{for(const r of db.prepare(`WITH persisted_members AS (${members.sql}) SELECT DISTINCT reportDate FROM persisted_members WHERE reportDate<>'' ORDER BY reportDate`).all(...members.params)){const d=dateKey(r.reportDate);if(d&&d<=to)set.add(d);}}catch{}for(const d of summaryFallback(type,to,db).keys())if(d<=to)set.add(d);if(type==='TBKH'&&hasTable(db,'metric_snapshots')){try{for(const r of db.prepare("SELECT DISTINCT reportDate FROM metric_snapshots WHERE businessType='TBKH' AND reportDate<=? ORDER BY reportDate").all(to)){const d=dateKey(r.reportDate);if(d)set.add(d);}}catch{}}const dates=[...set].sort();return dates.length>180?dates.slice(-180):dates;}

function shopeeFacts(type,from,to,db){const out=new Map(),members=membershipUnion(type,{from,to,db,upperOnly:false}),hasLedger=hasTable(db,'qc_tracking_ledger');const ledgerJoin=hasLedger?`LEFT JOIN qc_tracking_ledger l ON l.shipmentCode=m.shipmentCode AND l.businessType=?`:'';const ledgerFields=hasLedger?`,l.terminalReason,l.attemptNo ledgerAttemptNo,l.attemptSource,l.podDate ledgerPodDate,l.evidenceJson`:`,'' terminalReason,0 ledgerAttemptNo,'' attemptSource,'' ledgerPodDate,'{}' evidenceJson`;
  const sql=`WITH persisted_members AS (${members.sql}), members AS (SELECT reportDate,shipmentCode FROM persisted_members WHERE reportDate<>'' AND shipmentCode<>'' GROUP BY reportDate,shipmentCode), facts AS (
    SELECT m.reportDate,m.shipmentCode,CASE WHEN f.shipmentCode IS NULL${hasLedger?' AND l.shipmentCode IS NULL':''} THEN 0 ELSE 1 END matched,COALESCE(f.isPod,0) finalPod,COALESCE(f.primaryCategory,'') category,COALESCE(f.latestEventTime,'') latestEventTime,COALESCE(f.rawJson,'{}') rawJson,COALESCE(f.firstAttemptAt,'') firstAttemptAt,COALESCE(f.podAttemptNo,0) podAttemptNo,COALESCE(f.currentAttemptNo,0) currentAttemptNo,COALESCE(f.attemptStatus,'') attemptStatus,COALESCE(f.attemptConfidence,'') attemptConfidence,COALESCE(f.attemptHistoryJson,'') attemptHistoryJson${ledgerFields}
    FROM members m LEFT JOIN business_final_rows f ON f.reportDate=m.reportDate AND f.shipmentCode=m.shipmentCode AND f.businessType IN ('SHOPEE',?) ${ledgerJoin}
  ), normalized AS (
    SELECT *,CASE WHEN finalPod=1 OR terminalReason='POD' THEN 1 ELSE 0 END isPod,
      CASE WHEN finalPod=1 OR terminalReason='POD' THEN CASE WHEN attemptSource LIKE 'V246_STRICT_TRACK%' AND ledgerAttemptNo>0 THEN ledgerAttemptNo WHEN podAttemptNo>0 THEN podAttemptNo WHEN currentAttemptNo>0 AND (attemptConfidence='HIGH' OR attemptStatus LIKE '%STRICT%' OR attemptStatus LIKE 'V320%' OR attemptStatus LIKE 'V328%') THEN currentAttemptNo ELSE 0 END ELSE 0 END strictAttempt,
      COALESCE(NULLIF(CASE WHEN json_valid(evidenceJson) THEN json_extract(evidenceJson,'$.starts[0].time') END,''),NULLIF(firstAttemptAt,''),NULLIF(CASE WHEN json_valid(attemptHistoryJson) THEN json_extract(attemptHistoryJson,'$[0].time') END,''),NULLIF(CASE WHEN json_valid(attemptHistoryJson) THEN json_extract(attemptHistoryJson,'$.starts[0].time') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.firstAttemptAt') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.首次派件时间') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.首次派送时间') END,''),'') dispatchAt,
      COALESCE(NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.\"POD时间\"') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.podTime') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.\"签收时间\"') END,''),NULLIF(ledgerPodDate,''),'') podAt
    FROM facts
  ), norm AS (SELECT *,REPLACE(SUBSTR(dispatchAt,1,10),'/','-') dispatchDate,REPLACE(SUBSTR(podAt,1,10),'/','-') podDay FROM normalized)
  SELECT reportDate,COUNT(*) total,SUM(matched) matched,SUM(isPod) pod,SUM(CASE WHEN isPod=1 AND podDay=reportDate THEN 1 ELSE 0 END) sameDayPod,SUM(CASE WHEN isPod=0 AND matched=1 AND (category='OC' OR category LIKE 'OC%' OR category LIKE '%OC滞留%') THEN 1 ELSE 0 END) ocCurrent,
    SUM(CASE WHEN isPod=1 AND strictAttempt=1 THEN 1 ELSE 0 END) attempt1,SUM(CASE WHEN isPod=1 AND strictAttempt=2 THEN 1 ELSE 0 END) attempt2,SUM(CASE WHEN isPod=1 AND strictAttempt>=3 THEN 1 ELSE 0 END) attempt3,
    SUM(CASE WHEN isPod=1 AND dispatchDate<>'' AND podDay<>'' AND julianday(podDay)>=julianday(dispatchDate) THEN CAST(julianday(podDay)-julianday(dispatchDate)+1 AS INTEGER) ELSE 0 END) dispatchSigningDaysSum,SUM(CASE WHEN isPod=1 AND dispatchDate<>'' AND podDay<>'' AND julianday(podDay)>=julianday(dispatchDate) THEN 1 ELSE 0 END) dispatchSigningDaysCount FROM norm GROUP BY reportDate ORDER BY reportDate`;
  const params=[...members.params,type];if(hasLedger)params.push(type);try{for(const r of db.prepare(sql).all(...params))out.set(dateKey(r.reportDate),finish(type,r));}catch(error){console.warn('[CE-QC][V328_SHOPEE_FACTS_FAILED]',type,error?.message||error);}return out;}
function tbkhFacts(from,to,db){const type='TBKH',out=new Map(),members=membershipUnion(type,{from,to,db,upperOnly:false}),hasLedger=hasTable(db,'qc_tracking_ledger');const ledgerJoin=hasLedger?`LEFT JOIN qc_tracking_ledger l ON l.shipmentCode=m.shipmentCode AND l.businessType='TBKH'`:'';const ledgerFields=hasLedger?`,l.terminalReason,l.attemptNo ledgerAttemptNo,l.attemptSource,l.podDate ledgerPodDate,l.evidenceJson`:`,'' terminalReason,0 ledgerAttemptNo,'' attemptSource,'' ledgerPodDate,'{}' evidenceJson`;
  const sql=`WITH persisted_members AS (${members.sql}), members AS (SELECT reportDate,shipmentCode FROM persisted_members WHERE reportDate<>'' AND shipmentCode<>'' GROUP BY reportDate,shipmentCode), facts AS (
    SELECT m.reportDate,m.shipmentCode,CASE WHEN f.shipmentCode IS NULL${hasLedger?' AND l.shipmentCode IS NULL':''} THEN 0 ELSE 1 END matched,COALESCE(f.isPod,0) finalPod,COALESCE(f.primaryCategory,f.category,'') category,COALESCE(f.lastEventTime,'') latestEventTime,COALESCE(f.rawJson,'{}') rawJson${ledgerFields}
    FROM members m LEFT JOIN final_rows f ON f.reportDate=m.reportDate AND f.shipmentCode=m.shipmentCode ${ledgerJoin}
  ), normalized AS (
    SELECT *,CASE WHEN finalPod=1 OR terminalReason='POD' THEN 1 ELSE 0 END isPod,
      CASE WHEN finalPod=1 OR terminalReason='POD' THEN CASE WHEN attemptSource LIKE 'V246_STRICT_TRACK%' AND ledgerAttemptNo>0 THEN ledgerAttemptNo WHEN json_valid(rawJson) AND CAST(COALESCE(json_extract(rawJson,'$.podAttemptNo'),json_extract(rawJson,'$.currentAttemptNo'),0) AS INTEGER)>0 THEN CAST(COALESCE(json_extract(rawJson,'$.podAttemptNo'),json_extract(rawJson,'$.currentAttemptNo'),0) AS INTEGER) ELSE 0 END ELSE 0 END strictAttempt,
      COALESCE(NULLIF(CASE WHEN json_valid(evidenceJson) THEN json_extract(evidenceJson,'$.starts[0].time') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.firstAttemptAt') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.首次派件时间') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.首次派送时间') END,''),'') dispatchAt,
      COALESCE(NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.\"POD时间\"') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.podTime') END,''),NULLIF(CASE WHEN json_valid(rawJson) THEN json_extract(rawJson,'$.\"签收时间\"') END,''),NULLIF(ledgerPodDate,''),'') podAt FROM facts
  ), norm AS (SELECT *,REPLACE(SUBSTR(dispatchAt,1,10),'/','-') dispatchDate,REPLACE(SUBSTR(podAt,1,10),'/','-') podDay FROM normalized)
  SELECT reportDate,COUNT(*) total,SUM(matched) matched,SUM(isPod) pod,SUM(CASE WHEN isPod=1 AND podDay=reportDate THEN 1 ELSE 0 END) sameDayPod,SUM(CASE WHEN isPod=0 AND matched=1 AND (category='OC' OR category LIKE 'OC%' OR category LIKE '%OC滞留%') THEN 1 ELSE 0 END) ocCurrent,
    SUM(CASE WHEN isPod=1 AND strictAttempt=1 THEN 1 ELSE 0 END) attempt1,SUM(CASE WHEN isPod=1 AND strictAttempt=2 THEN 1 ELSE 0 END) attempt2,SUM(CASE WHEN isPod=1 AND strictAttempt>=3 THEN 1 ELSE 0 END) attempt3,
    SUM(CASE WHEN isPod=1 AND dispatchDate<>'' AND podDay<>'' AND julianday(podDay)>=julianday(dispatchDate) THEN CAST(julianday(podDay)-julianday(dispatchDate)+1 AS INTEGER) ELSE 0 END) dispatchSigningDaysSum,SUM(CASE WHEN isPod=1 AND dispatchDate<>'' AND podDay<>'' AND julianday(podDay)>=julianday(dispatchDate) THEN 1 ELSE 0 END) dispatchSigningDaysCount FROM norm GROUP BY reportDate ORDER BY reportDate`;
  try{for(const r of db.prepare(sql).all(...members.params))out.set(dateKey(r.reportDate),finish(type,r));}catch(error){console.warn('[CE-QC][V328_TBKH_FACTS_FAILED]',error?.message||error);}return out;}
function evidenceCache(type,from,to,db){const out=new Map();if(!hasTable(db,'v328_attempt_daily_cache'))return out;try{for(const r of db.prepare(`SELECT * FROM v328_attempt_daily_cache WHERE businessType=? AND reportDate BETWEEN ? AND ?`).all(type,from,to))out.set(dateKey(r.reportDate),r);}catch{}return out;}
function applyEvidenceCache(type,row,cached){if(!cached)return row;if(n(cached.total)!==n(row.total)||n(cached.pod)!==n(row.pod))return row;return finish(type,{...row,attempt1:n(cached.attempt1),attempt2:n(cached.attempt2),attempt3:n(cached.attempt3),dispatchSigningDaysSum:n(cached.signingDaysSum),dispatchSigningDaysCount:n(cached.signingDaysCount),evidenceCacheAt:cached.updatedAt||'',evidenceCacheSource:cached.source||'V328_BACKGROUND_EVIDENCE'});}

export function listV328HistoricalDates(businessType='',toDate='',db=getDb()){const type=String(businessType||'').toUpperCase();if(!TYPES.has(type))return[];return censusDates(type,toDate,db);}
export function listV328HistoricalMembers(businessType='',fromDate='',toDate='',db=getDb()){
  const type=String(businessType||'').toUpperCase(),from=dateKey(fromDate),to=dateKey(toDate);if(!TYPES.has(type)||!from||!to||from>to)return[];const members=membershipUnion(type,{from,to,db,upperOnly:false});try{return db.prepare(`WITH persisted_members AS (${members.sql}) SELECT reportDate,UPPER(TRIM(shipmentCode)) shipmentCode FROM persisted_members WHERE reportDate<>'' AND shipmentCode<>'' GROUP BY reportDate,UPPER(TRIM(shipmentCode)) ORDER BY reportDate,shipmentCode`).all(...members.params);}catch{return[];}}
export function readV328ThreeBusinessHistory(businessType='',toDate='',db=getDb()){
  const type=String(businessType||'').toUpperCase(),to=dateKey(toDate);if(!TYPES.has(type))throw new Error('V328历史读取仅支持TBKH、SHOPEECN、SHOPEEVN');if(!to)throw new Error('日期无效');const key=`${type}|${to}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.value;const dates=censusDates(type,to,db);if(!dates.length)return{ok:true,id:V328_THREE_BUSINESS_HISTORY_ID,businessType:type,requestedToDate:to,fromDate:to,toDate:to,dates:[],daily:[],historyExpanded:true,source:'V328_NO_PERSISTED_HISTORY'};const from=dates[0],last=dates.at(-1),facts=type==='TBKH'?tbkhFacts(from,last,db):shopeeFacts(type,from,last,db),summary=summaryFallback(type,last,db),evidence=evidenceCache(type,from,last,db);const daily=dates.map(d=>{let row=facts.get(d)||blank(type,d),sum=summary.get(d);if(sum&&(!row.total||row.matched<row.total)){row=finish(type,{...row,total:sum.total||row.total,pod:sum.pod,ocCurrent:sum.ocCurrent,sameDayPod:sum.sameDayPod,summaryReady:true,matched:Math.max(row.matched,sum.matched)});}row=applyEvidenceCache(type,row,evidence.get(d));return row;});const value={ok:true,id:V328_THREE_BUSINESS_HISTORY_ID,businessType:type,requestedToDate:to,fromDate:from,toDate:last,dates,daily,historyExpanded:true,availableDayCount:dates.length,evidenceIncomplete:daily.some(r=>r.evidenceIncomplete),source:'V328_PERSISTED_MEMBERSHIP_PLUS_FINAL_LEDGER_PLUS_BACKGROUND_EVIDENCE',definitions:{history:'TBKH、SHOPEE CN、SHOPEE VN统一自动读取各自已保存日报历史；只显示该板块真实存在且有成员/业务量的日报日期。',attempts:'1/2/3派统一使用真实70 START优先、整票无70才允许60兜底；失败/Pending后再次START才进入下一派。',averageDays:'平均派件→签收天数=真实首次派件START日至真实POD日的自然日平均，同日=1天；POD日期必须来自真实POD时间/锁定POD日期，不使用普通latestEventTime冒充签收时间。',missingEvidence:'历史POD缺轨迹START或真实POD日期时保持未知，由V328隔离后台证据修复补核，不把未知伪造成0。',performance:'页面仅读取本地索引成员、已保存终态和紧凑证据缓存；历史轨迹补核在独立子进程执行。'}};cache.set(key,{at:Date.now(),value});return value;}
export function clearV328ThreeBusinessHistoryCache(){cache.clear();}
console.info('[CE-QC][V328_THREE_BUSINESS_HISTORY]',V328_THREE_BUSINESS_HISTORY_ID,'TBKH + SHOPEECN + SHOPEEVN share persisted history, strict attempts, real dispatch→real POD timing, and optional background evidence cache; zero-only summary dates and unproven POD timestamps stay excluded/unknown.');