import { fork } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { V328_ATTEMPT_TYPES, clearV328ThreeBusinessHistoryCache } from './v328ThreeBusinessHistoryFast.js';

export const V328_EVIDENCE_COORDINATOR_ID='2026-08-27-v328-isolated-real-pod-evidence-repair-v2';
const TYPE_SET=new Set(V328_ATTEMPT_TYPES),states=new Map(V328_ATTEMPT_TYPES.map(type=>[type,{businessType:type,status:'IDLE',phase:'WAITING',toDate:'',total:0,completed:0,queried:0,failed:0,known:0,unresolved:0,message:'',updatedAt:'',completedAt:''}]));
const queue=new Map();let child=null,currentType='';
const workerPath=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../scripts/v328-three-business-evidence-worker-v2.mjs');
const now=()=>new Date().toISOString();
function patch(type,value={}){const old=states.get(type)||{businessType:type};states.set(type,{...old,...value,businessType:type,updatedAt:now()});return states.get(type);}
function spawnNext(){if(child||!queue.size)return;const [type,toDate]=queue.entries().next().value;queue.delete(type);currentType=type;patch(type,{status:'STARTING',phase:'STARTING',toDate,message:'启动历史派次/签收天数后台校准'});child=fork(workerPath,[`--type=${type}`,`--to=${toDate}`],{env:{...process.env,CE_QC_V328_CHILD:'1'},stdio:['ignore','ignore','ignore','ipc']});child.on('message',message=>{if(message?.kind!=='V328_EVIDENCE_PROGRESS')return;const status=String(message.status||'RUNNING').toUpperCase();patch(type,{...message,status,completedAt:status==='COMPLETED'?now():states.get(type)?.completedAt||''});if(status==='COMPLETED'){try{clearV328ThreeBusinessHistoryCache();}catch{}}});child.on('error',error=>patch(type,{status:'FAILED',phase:'FAILED',message:error?.message||String(error)}));child.on('exit',code=>{const state=states.get(type)||{};if(state.status==='STARTING'||state.status==='RUNNING')patch(type,{status:code===0?'COMPLETED':'FAILED',phase:code===0?'DONE':'FAILED',message:code===0?(state.message||'后台校准完成'):`后台校准子进程退出 code=${code}`});child=null;currentType='';setTimeout(spawnNext,750).unref?.();});}
export function requestV328EvidenceRepair(businessType='',toDate=''){const type=String(businessType||'').toUpperCase(),to=String(toDate||'').slice(0,10);if(!TYPE_SET.has(type)||!/\d{4}-\d{2}-\d{2}/.test(to))return inspectV328EvidenceRepair(type);const state=states.get(type)||{};if(['STARTING','RUNNING','QUEUED'].includes(state.status)&&state.toDate===to)return state;if(state.status==='COMPLETED'&&state.toDate===to){const age=Date.now()-Date.parse(state.completedAt||state.updatedAt||0),complete=Number(state.unresolved||0)===0&&Number(state.failed||0)===0,ttl=complete?4*60*60*1000:15*60*1000;if(age<ttl)return state;}queue.set(type,to);patch(type,{status:'QUEUED',phase:'QUEUED',toDate:to,message:child?`等待 ${currentType} 后台校准完成`:'等待后台校准启动'});setImmediate(spawnNext);return states.get(type);}
export function inspectV328EvidenceRepair(businessType=''){const type=String(businessType||'').toUpperCase();if(TYPE_SET.has(type))return{id:V328_EVIDENCE_COORDINATOR_ID,...states.get(type)};return{id:V328_EVIDENCE_COORDINATOR_ID,runningType:currentType,queue:[...queue.keys()],types:Object.fromEntries([...states.entries()])};}
console.info('[CE-QC][V328_EVIDENCE_COORDINATOR]',V328_EVIDENCE_COORDINATOR_ID,'TBKH + Shopee CN/VN historical START/POD evidence repair is demand-triggered in an isolated child; unresolved/network failures may retry after 15 minutes, while complete results stay warm for 4 hours.');
