import express from 'express';
import { getDb } from './db.js';
import { readV236CurrentSummary } from './v236DashboardCurrentRead.js';
import { readV334GenericHistoryCache,V334_GENERIC_HISTORY_TYPES,V334_GENERIC_HISTORY_CACHE_ID } from './v334GenericHistoryCache.js';
import { requestV334GenericHistoryBuild } from './v334GenericHistoryCoordinator.js';

export const V334_GENERIC_TREND_ROUTE_ID='2026-08-27-v334-generic-cache-only-v319-wrapper-v1';
const TYPES=new Set(V334_GENERIC_HISTORY_TYPES),STANDARD=['CE','CEAF','TBKH','ALI1688','SHOPEECN','SHOPEEVN'];
const originalGet=express.application.get;
const n=v=>Number.isFinite(Number(v))?Number(v):0,pct=(a,b)=>b?Number((n(a)*100/n(b)).toFixed(2)):0,date=v=>{const s=String(v||'').slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';};
function blank(type,d){return{businessType:type,reportDate:d,total:0,pod:0,ocCurrent:0,sameDayPod:0,podRate:0,ocRate:0,sameDayPodRate:0,ready:false};}
function add(out,row={}){out.total+=n(row.total);out.pod+=n(row.pod);out.ocCurrent+=n(row.ocCurrent);out.sameDayPod+=n(row.sameDayPod);}
function current(type,d){const summary=readV236CurrentSummary(d,{cacheOnly:true});if(type==='WHPP')return summary.whpp||blank(type,d);if(STANDARD.includes(type))return summary.business?.[type]||blank(type,d);if(type==='ALL'){const out=blank('ALL',d),parts=[...STANDARD.map(t=>summary.business?.[t]),summary.whpp].filter(Boolean);for(const row of parts)add(out,row);out.ready=parts.length>0&&parts.every(row=>row.ready!==false);out.podRate=pct(out.pod,out.total);out.ocRate=pct(out.ocCurrent,out.total);out.sameDayPodRate=pct(out.sameDayPod,out.total);return out;}return blank(type,d);}
function shape(type,from,to,data,repair){const daily=Array.isArray(data?.daily)?data.daily:[],dates=daily.map(row=>String(row.reportDate||''));return{ok:true,id:V334_GENERIC_TREND_ROUTE_ID,readId:V334_GENERIC_HISTORY_CACHE_ID,businessType:type,requestedFromDate:from,requestedToDate:to,fromDate:dates[0]||from,toDate:dates.at(-1)||to,dates,daily,ticket:daily.map(r=>n(r.total)),pod:daily.map(r=>r.ready===false?null:n(r.pod)),podRate:daily.map(r=>r.ready===false?null:r.podRate),oc:daily.map(r=>r.ready===false?null:n(r.ocCurrent)),ocRate:daily.map(r=>r.ready===false?null:r.ocRate),sameDayPod:daily.map(r=>r.ready===false?null:n(r.sameDayPod)),sameDayPodRate:daily.map(r=>r.ready===false?null:r.sameDayPodRate),missingDates:daily.filter(r=>r.ready===false).map(r=>r.reportDate),historyExpanded:true,historyCachePending:['QUEUED','STARTING','RUNNING'].includes(String(repair?.status||'').toUpperCase()),evidenceRepair:repair,source:`V334_GENERIC_CACHE_ONLY:${data?.source||'EMPTY'}`,definitions:{history:'顶部单日日期只控制当天卡片；趋势读取截至该日已保存历史缓存。缓存重建在独立子进程运行，网页不扫描历史大表。'}};}
function handler(req,res){try{const started=Date.now(),type=String(req.query.businessType||'').toUpperCase(),from=date(req.query.from),to=date(req.query.to),historyAll=String(req.query.history||'').toLowerCase()==='all';if(!TYPES.has(type)||!from||!to||from>to)return null;const repair=requestV334GenericHistoryBuild(type,to),cached=readV334GenericHistoryCache(type,to,getDb(),historyAll?'':from);let payload;if(cached.daily.length)payload=shape(type,from,to,cached,repair);else{const row=current(type,to),fallback={daily:row.total>0||row.ready?[row]:[],source:'V334_CURRENT_DAY_FALLBACK'};payload=shape(type,from,to,fallback,repair);payload.historyCachePending=true;}res.setHeader('Cache-Control','private,max-age=5');res.setHeader('X-CE-QC-V334',V334_GENERIC_TREND_ROUTE_ID);res.setHeader('Server-Timing',`v334generic;dur=${Date.now()-started}`);res.json(payload);return true;}catch(error){res.status(400).json({ok:false,id:V334_GENERIC_TREND_ROUTE_ID,error:error?.message||String(error)});return true;}}
express.application.get=function v334GenericTrendRegistration(pathValue,...handlers){if(pathValue==='/api/v319/trends'&&handlers.length){const originalHandler=handlers.at(-1);handlers[handlers.length-1]=function v334GenericHistoryAwareV319(req,res,next){const type=String(req.query?.businessType||'').toUpperCase(),from=date(req.query?.from),to=date(req.query?.to),historyAll=String(req.query?.history||'').toLowerCase()==='all';if(TYPES.has(type)&&from&&to&&(historyAll||from!==to)){const handled=handler(req,res);if(handled)return;}return originalHandler(req,res,next);};}return originalGet.call(this,pathValue,...handlers);};
console.info('[CE-QC][V334_GENERIC_TREND_ROUTE]',V334_GENERIC_TREND_ROUTE_ID,'generic V319 history=all and explicit ranges are cache-only; ordinary one-day V319 first paint remains untouched.');
